// <auto-generated />
using System;
using HaoKao.GroupBookingService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.GroupBookingService.Infrastructure.Migrations
{
    [DbContext(typeof(GroupBookingDbContext))]
    partial class GroupBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.GroupBookingService.Domain.Entities.GroupData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BasePeopleNumber")
                        .HasColumnType("int")
                        .HasComment("基础拼团成功人数");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DataName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("资料名");

                    b.Property<string>("Document")
                        .HasColumnType("text")
                        .HasComment("拼团资料");

                    b.Property<int>("LimitTime")
                        .HasColumnType("int")
                        .HasComment("限制时间");

                    b.Property<int>("PeopleNumber")
                        .HasColumnType("int")
                        .HasComment("成团人数");

                    b.Property<ulong?>("State")
                        .HasColumnType("bit")
                        .HasComment("状态");

                    b.Property<string>("SuitableSubjects")
                        .HasColumnType("json")
                        .HasComment("适用科目");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("GroupData", (string)null);
                });

            modelBuilder.Entity("HaoKao.GroupBookingService.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("用户Id");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("组团过期时间");

                    b.Property<Guid>("GroupDataId")
                        .HasColumnType("char(36)")
                        .HasComment("拼团资料Id");

                    b.Property<Guid>("GroupSituationId")
                        .HasColumnType("char(36)")
                        .HasComment("拼团情况Id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasComment("用户头像Url");

                    b.Property<ulong>("IsLeader")
                        .HasColumnType("bit")
                        .HasComment("是否团长");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("昵称");

                    b.Property<DateTime?>("SuccessTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("组团成功时间");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupSituationId");

                    b.HasIndex("CreatorId", "GroupDataId", "TenantId");

                    b.ToTable("GroupMember", (string)null);
                });

            modelBuilder.Entity("HaoKao.GroupBookingService.Domain.Entities.GroupSituation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DataName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("资料名");

                    b.Property<string>("Document")
                        .HasColumnType("text")
                        .HasComment("拼团资料");

                    b.Property<Guid>("GroupDataId")
                        .HasColumnType("char(36)")
                        .HasComment("组团资料Id");

                    b.Property<int>("LimitTime")
                        .HasColumnType("int")
                        .HasComment("限制时间");

                    b.Property<int>("PeopleNumber")
                        .HasColumnType("int")
                        .HasComment("成团人数");

                    b.Property<DateTime?>("SuccessTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("组团成功时间");

                    b.Property<string>("SuitableSubjects")
                        .HasColumnType("json")
                        .HasComment("适用科目");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("GroupDataId", "SuccessTime", "DataName", "TenantId");

                    b.ToTable("GroupSituation", (string)null);
                });

            modelBuilder.Entity("HaoKao.GroupBookingService.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("HaoKao.GroupBookingService.Domain.Entities.GroupSituation", "GroupSituation")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupSituationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupSituation");
                });

            modelBuilder.Entity("HaoKao.GroupBookingService.Domain.Entities.GroupSituation", b =>
                {
                    b.Navigation("GroupMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
