// <auto-generated />
using System;
using HaoKao.QuestionCategoryService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.QuestionCategoryService.Infrastructure.Migrations
{
    [DbContext(typeof(QuestionCategoryDbContext))]
    [Migration("20240821031433_AddProductPackage")]
    partial class AddProductPackage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.QuestionCategoryService.Domain.Entities.QuestionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("AdaptPlace")
                        .HasColumnType("bigint")
                        .HasComment("适应场景");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("类别代码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<int>("DisplayCondition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("显示条件");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("类名名称");

                    b.Property<Guid>("ProductPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasComment("产品包Id(购买跳转对象)");

                    b.Property<int?>("ProductPackageType")
                        .HasColumnType("int")
                        .HasComment("产品包类型");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.HasIndex("AdaptPlace", "Name", "TenantId");

                    b.ToTable("QuestionCategory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
