// <auto-generated />
using System;
using HaoKao.OrderService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20230615081419_addIosIsOpen")]
    partial class addIosIsOpen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.OrderService.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ActualAmount")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("实际金额");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientName")
                        .HasColumnType("varchar(50)")
                        .HasComment("购买商品详细内容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("OrderAmount")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("订单金额");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("订单号");

                    b.Property<string>("OrderSerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasComment("订单第三方流水号");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<Guid>("PlatformPayerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PlatformPayerName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("使用的平台配置的支付者的名称");

                    b.Property<string>("PurchaseName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("购买产品名称");

                    b.Property<string>("PurchaseProductContents")
                        .HasColumnType("text")
                        .HasComment("购买商品详细内容");

                    b.Property<Guid>("PurchaseProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PurchaseProductType")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TenantName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderSerialNumber")
                        .IsUnique();

                    b.HasIndex("OrderNumber", "PurchaseName", "CreatorName", "CreateTime", "UpdateTime", "OrderState", "PurchaseProductType", "TenantId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("HaoKao.OrderService.Domain.Models.PlatformPayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Config")
                        .HasColumnType("text")
                        .HasComment("支付相关配置");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IosIsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("Ios是否开启");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("支付名称");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PayerName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("对应支付处理者名称");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PlatformPayerScenes")
                        .HasColumnType("int");

                    b.Property<string>("SecurityCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasComment("数据安全码");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("更新时间");

                    b.Property<bool>("UseState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasComment("启用/禁用");

                    b.HasKey("Id");

                    b.ToTable("PlatformPayer", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
