// <auto-generated />
using System;
using HaoKao.NotificationMessageService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.NotificationMessageService.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationMessageDbContext))]
    [Migration("20241218083101_addSmsTemplate1")]
    partial class addSmsTemplate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.NotificationMessageService.Domain.Models.InSiteMessageSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppId")
                        .HasColumnType("varchar(100)")
                        .HasComment("短信平台 AppId");

                    b.Property<string>("AppSecret")
                        .HasColumnType("varchar(200)")
                        .HasComment("短信平台 AppSecret");

                    b.Property<string>("Templates")
                        .HasColumnType("json")
                        .HasComment("模板配置");

                    b.HasKey("Id");

                    b.ToTable("InSiteMessageSetting", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f579602-853c-482b-893f-48f755e4cc40"),
                            Templates = "[{\"NotificationMessageType\":4,\"TemplateId\":\"您报考的{0}考试已完成{1}，请继续报考并在报名时间内完成报考。\",\"Desc\":\"您报考的{0}考试已完成{1}，请继续报考并在报名时间内完成报考。\"}]"
                        });
                });

            modelBuilder.Entity("HaoKao.NotificationMessageService.Domain.Models.MobileMessageSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppId")
                        .HasColumnType("varchar(100)")
                        .HasComment("短信平台 AppId");

                    b.Property<string>("AppSecret")
                        .HasColumnType("varchar(200)")
                        .HasComment("短信平台 AppSecret");

                    b.Property<string>("DefaultSign")
                        .HasColumnType("varchar(40)")
                        .HasComment("默认签名");

                    b.Property<int>("MobileMessagePlatform")
                        .HasColumnType("int");

                    b.Property<string>("SignList")
                        .HasColumnType("varchar(4000)")
                        .HasComment("签名列表");

                    b.Property<string>("SmsSdkAppId")
                        .HasColumnType("varchar(100)")
                        .HasComment("短信SDk 应用ID");

                    b.Property<string>("Templates")
                        .HasColumnType("json")
                        .HasComment("模板配置");

                    b.HasKey("Id");

                    b.ToTable("MobileMessageSetting", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d26043f7-c92f-4265-b859-44fcce01212c"),
                            AppId = "AKIDKVVGbCYdS2oMQFbADE9qHSdbKBc2ayR6",
                            AppSecret = "rU1JXgeU9dttds1uYzISRAOBj36tGQVW",
                            DefaultSign = "好慧考",
                            MobileMessagePlatform = 1,
                            SignList = "好慧考,经济师云课堂",
                            SmsSdkAppId = "1400559681",
                            Templates = "[{\"NotificationMessageType\":0,\"TemplateId\":\"1073230\",\"Desc\":\"您正在申请手机注册，验证码为：{1}，{2}分钟内有效！\"},{\"NotificationMessageType\":1,\"TemplateId\":\"1074912\",\"Desc\":\"{1}为您的登录验证码，请于{2}分钟内填写。\"},{\"NotificationMessageType\":2,\"TemplateId\":\"1076233\",\"Desc\":\"{1}为您的找回密码验证码，请于{2}分钟内填写。\"},{\"NotificationMessageType\":3,\"TemplateId\":\"1253909\",\"Desc\":\"验证码：{1}，您正在进行变更手机号操作，验证码{2}分钟内有效。请勿将验证码告知他人。\"},{\"NotificationMessageType\":4,\"TemplateId\":\"1403274\",\"Desc\":\"您好，您本次报名的{1}，完成{2}环节执行，状态为：{3}，如非本人操作，请忽略本短信。\"},{\"NotificationMessageType\":5,\"TemplateId\":\"1220437\",\"Desc\":\"您好，恭喜您{1} 报名成功，请留意考试时间。\"},{\"NotificationMessageType\":6,\"TemplateId\":\"2121845\",\"Desc\":\"您预约的“{1}”还有5分钟（{2}）就要开播啦，记得来听课哟！\"},{\"NotificationMessageType\":8,\"TemplateId\":\"2271962\",\"Desc\":\"下午好，好慧考小助手查询到您几日未开展学习，马上要临考了，请抓紧时间观看课程哦 \"},{\"NotificationMessageType\":9,\"TemplateId\":\"2271964\",\"Desc\":\"忙完了，请记得每日学习 \"},{\"NotificationMessageType\":10,\"TemplateId\":\"2271969\",\"Desc\":\"每天学习两小时，早日上岸，加油 \"},{\"NotificationMessageType\":11,\"TemplateId\":\"2271971\",\"Desc\":\"学习是每天的头等大事！！\"},{\"NotificationMessageType\":12,\"TemplateId\":\"2271972\",\"Desc\":\"好慧考温馨提醒：课程学完了，可进入题库作答巩固知识点哦~ \"},{\"NotificationMessageType\":13,\"TemplateId\":\"2332823\",\"Desc\":\"学员您好，我是好慧考班主任—伊伊。您已购买课程，请添加老师的企业微信（18975172696），以便后续服务。\"},{\"NotificationMessageType\":14,\"TemplateId\":\"2332824\",\"Desc\":\"学员您好，我是好慧考班主任—左左。您已购买课程，请添加老师的企业微信（17388982296），以便后续服务。\"}]"
                        });
                });

            modelBuilder.Entity("HaoKao.NotificationMessageService.Domain.Models.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorName")
                        .HasColumnType("varchar(50)")
                        .HasComment("创建者");

                    b.Property<string>("Failure")
                        .HasColumnType("varchar(255)")
                        .HasComment("发送失败内容");

                    b.Property<string>("IdCard")
                        .HasColumnType("varchar(18)")
                        .HasComment("身份证号码");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MessageTemplateId")
                        .HasColumnType("varchar(100)")
                        .HasComment("消息模板Id");

                    b.Property<int>("NotificationMessageType")
                        .HasColumnType("int");

                    b.Property<string>("ParameterContent")
                        .HasColumnType("varchar(500)")
                        .HasComment("消息内容");

                    b.Property<string>("Receiver")
                        .HasColumnType("varchar(50)")
                        .HasComment("接收者");

                    b.Property<long>("ReceivingChannel")
                        .HasColumnType("bigint");

                    b.Property<int>("SendState")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(100)")
                        .HasComment("消息标题");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime", "Receiver", "ParameterContent", "Title", "IdCard", "NotificationMessageType", "ReceivingChannel", "SendState", "IsRead");

                    b.ToTable("NotificationMessage", (string)null);
                });

            modelBuilder.Entity("HaoKao.NotificationMessageService.Domain.Models.TenantSignSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Sign")
                        .HasColumnType("varchar(100)")
                        .HasComment("租户签名名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("TenantSignSetting", (string)null);
                });

            modelBuilder.Entity("HaoKao.NotificationMessageService.Domain.Models.WechatMessageSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AppSecret")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Templates")
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.ToTable("WechatMessageSetting", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3032e7b-477f-4922-8054-e61a45610a49"),
                            AppId = "wx1917f27b2522e1ce",
                            AppSecret = "4fd38646436d0a5110f76ffedfbf90dd",
                            Templates = "[{\"NotificationMessageType\":6,\"TemplateId\":\"Gtqw_tKWsvH07P7o-Fvkzgfg78opmDJs-7d696daWOM\",\"Desc\":\"直播开播提醒\\n直播间名称: {{thing6.DATA}}\\n开播时间: {{date7.DATA}}\"},{\"NotificationMessageType\":7,\"TemplateId\":\"v3NjkJkYissNTiBO4SDJwrC1A_bQNjuT2zqsXBdXuuM\",\"Desc\":\"温馨提示: 卡券即将到期，点击查看详情使用\\n卡券名称: {{thing2.DATA}}\\n过期时间: {{time3.DATA}}\"}]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
