// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortUrlService.Infrastructure;

namespace ShortUrlService.Infrastructure.Migrations
{
    [DbContext(typeof(ShortUrlDbContext))]
    partial class ShortUrlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ShortUrlService.Domain.Entities.AccessLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("BrowserType")
                        .HasColumnType("int")
                        .HasComment("浏览器类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("访问时间");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("IP地址");

                    b.Property<int>("OsType")
                        .HasColumnType("int")
                        .HasComment("系统类型");

                    b.Property<long>("ShortUrlId")
                        .HasColumnType("bigint")
                        .HasComment("短链接Id");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("UserAgent");

                    b.HasKey("Id");

                    b.HasIndex("ShortUrlId");

                    b.ToTable("AccessLog", (string)null);
                });

            modelBuilder.Entity("ShortUrlService.Domain.Entities.RegisterApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("应用编码");

                    b.Property<string>("AppDomains")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasComment("应用域名");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("应用名称");

                    b.Property<string>("AppSecret")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasComment("应用密钥");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasComment("应用描述");

                    b.Property<bool>("IsEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasComment("是否启用");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("修改时间");

                    b.HasKey("Id");

                    b.HasIndex("AppCode", "AppSecret")
                        .IsUnique();

                    b.HasIndex("AppName", "AppCode")
                        .IsUnique();

                    b.ToTable("RegisterApp", (string)null);
                });

            modelBuilder.Entity("ShortUrlService.Domain.Entities.ShortUrl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessLimit")
                        .HasColumnType("int")
                        .HasComment("可访问次数");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("过期时间");

                    b.Property<ulong>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul)
                        .HasComment("是否删除标识");

                    b.Property<string>("OriginUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("原始Url");

                    b.Property<long>("RegisterAppId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("短链接后缀");

                    b.HasKey("Id");

                    b.HasIndex("ShortKey", "IsDelete");

                    b.HasIndex("RegisterAppId", "OriginUrl", "IsDelete");

                    b.ToTable("ShortUrl", (string)null);
                });

            modelBuilder.Entity("ShortUrlService.Domain.Entities.AccessLog", b =>
                {
                    b.HasOne("ShortUrlService.Domain.Entities.ShortUrl", null)
                        .WithMany("AccessLogs")
                        .HasForeignKey("ShortUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShortUrlService.Domain.Entities.ShortUrl", b =>
                {
                    b.HasOne("ShortUrlService.Domain.Entities.RegisterApp", null)
                        .WithMany("ShortUrls")
                        .HasForeignKey("RegisterAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShortUrlService.Domain.Entities.RegisterApp", b =>
                {
                    b.Navigation("ShortUrls");
                });

            modelBuilder.Entity("ShortUrlService.Domain.Entities.ShortUrl", b =>
                {
                    b.Navigation("AccessLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
