// <auto-generated />
using System;
using HaoKao.AnsweringQuestionService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.AnsweringQuestionService.Infrastructure.Migrations
{
    [DbContext(typeof(AnsweringQuestionDbContext))]
    [Migration("20230808061157_innitdatabase20230831")]
    partial class innitdatabase20230831
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.AnsweringQuestionService.Domain.Models.AnsweringQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BookName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("书籍名称以及相关描述");

                    b.Property<string>("BookPageSize")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("书籍页码");

                    b.Property<Guid>("CourseChapterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseChapterName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CourseVideId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseVideName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("问题描述");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("上传的图片路劲");

                    b.Property<bool>("IsReply")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("手机号码");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("详细描述");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("用户名称");

                    b.Property<int>("WatchCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AnsweringQuestion", (string)null);
                });

            modelBuilder.Entity("HaoKao.AnsweringQuestionService.Domain.Models.AnsweringQuestionReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnsweringQuestionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ReplyContent")
                        .HasColumnType("longtext")
                        .HasComment("答疑回复内容");

                    b.Property<string>("ReplyUserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("回复人用户名");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("AnsweringQuestionId");

                    b.ToTable("AnsweringQuestionReply", (string)null);
                });

            modelBuilder.Entity("HaoKao.AnsweringQuestionService.Domain.Models.AnsweringQuestion", b =>
                {
                    b.HasOne("HaoKao.AnsweringQuestionService.Domain.Models.AnsweringQuestion", null)
                        .WithMany("ChildQuestion")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("HaoKao.AnsweringQuestionService.Domain.Models.AnsweringQuestionReply", b =>
                {
                    b.HasOne("HaoKao.AnsweringQuestionService.Domain.Models.AnsweringQuestion", null)
                        .WithMany("AnsweringQuestionReplys")
                        .HasForeignKey("AnsweringQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.AnsweringQuestionService.Domain.Models.AnsweringQuestion", b =>
                {
                    b.Navigation("AnsweringQuestionReplys");

                    b.Navigation("ChildQuestion");
                });
#pragma warning restore 612, 618
        }
    }
}
