// <auto-generated />
using System;
using HaoKao.ProductService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaoKao.ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20230906061453_addSort")]
    partial class addSort
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Agreement")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Answering")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AppleProductId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasComment("苹果内购产品ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("产品描述");

                    b.Property<string>("DetailImage")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("产品详情介绍图片");

                    b.Property<double>("DiscountedPrice")
                        .HasPrecision(6, 2)
                        .HasColumnType("double")
                        .HasComment("优惠价格");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GiveAwayAList")
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)")
                        .HasComment("赠送列表");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("产品图标图片");

                    b.Property<bool>("IsShelves")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("产品名称");

                    b.Property<double>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("double")
                        .HasComment("价格");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.ProductPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CardImage")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("产品卡片图片");

                    b.Property<bool>("Contrast")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasComment("对比详细介绍");

                    b.Property<string>("DetailImage")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("详细介绍图片");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime")
                        .HasComment("到期时间");

                    b.Property<string>("FeaturedService")
                        .HasColumnType("text")
                        .HasComment("特色服务");

                    b.Property<bool>("Hot")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("名称");

                    b.Property<DateTime>("PreferentialExpiryTime")
                        .HasColumnType("datetime")
                        .HasComment("优惠到期时间");

                    b.Property<string>("ProductList")
                        .HasColumnType("text")
                        .HasComment("对应的产品列表");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<string>("Selling")
                        .HasColumnType("text")
                        .HasComment("卖点");

                    b.Property<bool>("Shelves")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime")
                        .HasComment("所属年份");

                    b.HasKey("Id");

                    b.ToTable("ProductPackage", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.ProductPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("产品权限属性分类");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("产品权限名称");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPermission", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.StudentPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime")
                        .HasComment("到期时间");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("对应的订单号");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("产品名称");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int>("SourceMode")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StudentName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("学员昵称(即用户昵称)");

                    b.HasKey("Id");

                    b.ToTable("StudentPermission", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.ProductPermission", b =>
                {
                    b.HasOne("HaoKao.ProductService.Domain.Entities.Product", "Product")
                        .WithMany("ProductPermissions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
