// <auto-generated />
using System;
using HaoKao.ProductService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaoKao.ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.AssistantProductPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssistantProductPermissionContents")
                        .HasColumnType("json")
                        .HasComment("智辅产品权限内容");

                    b.Property<Guid>("CourseStageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseStageName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("课程阶段名称");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasColumnType("varchar(50)")
                        .HasComment("对应科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SubjectId", "TenantId");

                    b.ToTable("AssistantProductPermission", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Agreement")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Answering")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AppleProductId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasComment("苹果内购产品ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("varchar(40)")
                        .HasComment("创建人名称");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasComment("产品描述");

                    b.Property<string>("DetailImage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasComment("产品详情介绍图片");

                    b.Property<double>("DiscountedPrice")
                        .HasPrecision(6, 2)
                        .HasColumnType("double")
                        .HasComment("优惠价格");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("显示名称");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExpiryTimeTypeEnum")
                        .HasColumnType("int");

                    b.Property<string>("GiveAwayAList")
                        .HasColumnType("json")
                        .HasComment("赠送列表");

                    b.Property<string>("Icon")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasComment("产品图标图片");

                    b.Property<bool>("IsExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否体验产品");

                    b.Property<bool>("IsShelves")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("产品名称");

                    b.Property<double>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("double")
                        .HasComment("价格");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int>("ReservationBaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasComment("年份");

                    b.HasKey("Id");

                    b.HasIndex("ProductType", "Year", "Enable", "IsShelves", "TenantId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.ProductPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CardImage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasComment("产品卡片图片");

                    b.Property<Guid?>("ComparisonDictionaryId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Contrast")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("varchar(40)")
                        .HasComment("创建人名称");

                    b.Property<string>("Desc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasComment("描述");

                    b.Property<string>("Detail")
                        .HasColumnType("json")
                        .HasComment("对比详细介绍");

                    b.Property<string>("DetailImage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasComment("详细介绍图片");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime")
                        .HasComment("到期时间");

                    b.Property<string>("FeaturedService")
                        .HasColumnType("json")
                        .HasComment("特色服务");

                    b.Property<bool>("Hot")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否体验产品包");

                    b.Property<bool>("IsSupportInstallmentPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否支持分期支付");

                    b.Property<string>("LecturerList")
                        .HasColumnType("json")
                        .HasComment("讲师列表");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("名称");

                    b.Property<int>("NumberOfBuyers")
                        .HasColumnType("int");

                    b.Property<DateTime>("PreferentialExpiryTime")
                        .HasColumnType("datetime")
                        .HasComment("优惠到期时间");

                    b.Property<string>("ProductList")
                        .HasColumnType("json")
                        .HasComment("对应的产品列表");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<string>("SalesRemind")
                        .HasColumnType("text")
                        .HasComment("售后提醒");

                    b.Property<string>("Selling")
                        .HasColumnType("json")
                        .HasComment("卖点");

                    b.Property<bool>("Shelves")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SimpleDesc")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("简单描述");

                    b.Property<string>("SimpleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("简称");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime")
                        .HasComment("所属年份");

                    b.HasKey("Id");

                    b.HasIndex("ProductType", "Year", "Enable", "Shelves", "TenantId");

                    b.ToTable("ProductPackage", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.ProductPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("产品权限属性分类");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("产品权限名称");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PermissionId", "TenantId");

                    b.ToTable("ProductPermission", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.RelatedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("创建人名称");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("产品名称");

                    b.Property<string>("RelatedTargetProducName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("关联对象产品名称");

                    b.Property<Guid>("RelatedTargetProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("RelatedProduct", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.StudentPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime")
                        .HasComment("到期时间");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("对应的订单号");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasComment("产品名称");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int>("SourceMode")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StudentName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("学员昵称(即用户昵称)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "TenantId");

                    b.HasIndex("ProductId", "Enable", "TenantId");

                    b.HasIndex("StudentId", "ProductId", "Enable");

                    b.ToTable("StudentPermission", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.StudentPermissionOperateLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("创建人Id");

                    b.Property<DateTime>("NewExpiredTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("现过期时间");

                    b.Property<DateTime?>("OldExpiredTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("原过期时间");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasComment("产品Id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("产品名称");

                    b.Property<int>("ProductType")
                        .HasColumnType("int")
                        .HasComment("产品类型");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)")
                        .HasComment("学员ID（即用户ID）");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("学员昵称(即用户昵称)");

                    b.Property<Guid>("StudentPermissionId")
                        .HasColumnType("char(36)")
                        .HasComment("学员权限Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime", "StudentName");

                    b.ToTable("StudentPermissionOperateLog", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.SupervisorClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("班级名称");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("产品名称");

                    b.Property<Guid>("ProductPackageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductPackageName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("产品包名称");

                    b.Property<Guid>("SalespersonId")
                        .HasColumnType("char(36)")
                        .HasComment("营销人员Id");

                    b.Property<string>("SalespersonName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("营销人员名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Year", "TenantId");

                    b.ToTable("SupervisorClass", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.SupervisorStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CourseCount")
                        .HasColumnType("int");

                    b.Property<float>("CourseDuration")
                        .HasColumnType("float");

                    b.Property<float>("CourseRatio")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("IsEndCourseCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLearnTime")
                        .HasColumnType("datetime")
                        .HasComment("最近学习时间");

                    b.Property<float>("MaxProgress")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("昵称");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("手机号");

                    b.Property<Guid>("RegisterUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StatisticsTime")
                        .HasColumnType("datetime")
                        .HasComment("统计时间 （每一天只统计一次）");

                    b.Property<Guid>("SupervisorClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorClassId");

                    b.ToTable("SupervisorStudent", (string)null);
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.AssistantProductPermission", b =>
                {
                    b.HasOne("HaoKao.ProductService.Domain.Entities.Product", null)
                        .WithMany("AssistantProductPermissions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.ProductPermission", b =>
                {
                    b.HasOne("HaoKao.ProductService.Domain.Entities.Product", null)
                        .WithMany("ProductPermissions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.RelatedProduct", b =>
                {
                    b.HasOne("HaoKao.ProductService.Domain.Entities.Product", "Product")
                        .WithMany("RelatedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.SupervisorStudent", b =>
                {
                    b.HasOne("HaoKao.ProductService.Domain.Entities.SupervisorClass", "SupervisorClass")
                        .WithMany("SupervisorStudents")
                        .HasForeignKey("SupervisorClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupervisorClass");
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.Product", b =>
                {
                    b.Navigation("AssistantProductPermissions");

                    b.Navigation("ProductPermissions");

                    b.Navigation("RelatedProducts");
                });

            modelBuilder.Entity("HaoKao.ProductService.Domain.Entities.SupervisorClass", b =>
                {
                    b.Navigation("SupervisorStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
