// <auto-generated />
using System;
using HaoKao.LearningPlanService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.LearningPlanService.Infrastructure.Migrations
{
    [DbContext(typeof(LearningPlanDbContext))]
    [Migration("20250731071847_addInitData")]
    partial class addInitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.LearningPlanService.Domain.Entities.LearningPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DayLearningTimes")
                        .HasColumnType("json")
                        .HasComment("每周学习时长配置(分钟)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasComment("学习计划结束日期");

                    b.Property<bool>("NeedReminder")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReminderHours")
                        .HasColumnType("int");

                    b.Property<int>("ReminderMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ReminderPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("提醒手机号");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("对应科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("LearningPlan", (string)null);
                });

            modelBuilder.Entity("HaoKao.LearningPlanService.Domain.Entities.LearningTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("DurationSeconds")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(7,2)")
                        .HasComment("完成该任务预计需要的时长（秒），支持小数表示");

                    b.Property<Guid>("LearningPlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("ScheduledTime")
                        .HasColumnType("date")
                        .HasComment("计划开始该任务的时间点");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("TaskContent")
                        .HasColumnType("json")
                        .HasComment("任务内容");

                    b.Property<string>("TaskIdentity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("任务标识（用于重新制作学习计划时判定当前任务内容是否已是过期任务内容）");

                    b.Property<string>("TaskName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("任务名称");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("LearningPlanId");

                    b.HasIndex("ScheduledTime", "LearningPlanId");

                    b.ToTable("LearningTask", (string)null);
                });

            modelBuilder.Entity("HaoKao.LearningPlanService.Domain.Entities.LearningTask", b =>
                {
                    b.HasOne("HaoKao.LearningPlanService.Domain.Entities.LearningPlan", "LearningPlan")
                        .WithMany("LearningTasks")
                        .HasForeignKey("LearningPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPlan");
                });

            modelBuilder.Entity("HaoKao.LearningPlanService.Domain.Entities.LearningPlan", b =>
                {
                    b.Navigation("LearningTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
