// <auto-generated />
using System;
using HaoKao.ChapterNodeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.ChapterNodeService.Infrastructure.Migrations
{
    [DbContext(typeof(ChapterNodeDbContext))]
    [Migration("20230504065809_changeIndexType")]
    partial class changeIndexType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.ChapterNodeService.Domain.Entities.ChapterNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("章节名称");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ParentIds")
                        .HasColumnType("longtext")
                        .HasComment("父级Id集合");

                    b.Property<string>("ParentName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("父级名称");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "ParentId", "TenantId");

                    b.ToTable("ChapterNode", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
