// <auto-generated />
using System;
using HaoKao.ChapterNodeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.ChapterNodeService.Infrastructure.Migrations
{
    [DbContext(typeof(ChapterNodeDbContext))]
    [Migration("20250610074240_addKnowledgePoint")]
    partial class addKnowledgePoint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.ChapterNodeService.Domain.ChapterNodeRelevant.ChapterNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("章节名称");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ParentIds")
                        .HasColumnType("longtext")
                        .HasComment("父级Id集合");

                    b.Property<string>("ParentName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("父级名称");

                    b.Property<string>("PropertyValueID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("从题库迁移的数据");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "ParentId", "TenantId");

                    b.ToTable("ChapterNode", (string)null);
                });

            modelBuilder.Entity("HaoKao.ChapterNodeService.Domain.KnowledgePointRelevant.KnowledgePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChapterNodeId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("章节Id");

                    b.Property<string>("ChapterNodeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasComment("章节名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("ExamFrequency")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasComment("知识点名称");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterNodeId", "Name", "TenantId");

                    b.ToTable("KnowledgePoint", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
