// Global using directives
global using AutoMapper;
global using Girvs;
global using Girvs.AuthorizePermission;
global using Girvs.AutoMapper.Extensions;
global using Girvs.AutoMapper.Mapper;
global using Girvs.BusinessBasis;
global using Girvs.BusinessBasis.Dto;
global using Girvs.Cache.Caching;
global using Girvs.Driven.Bus;
global using Girvs.Driven.Notifications;
global using Girvs.DynamicWebApi;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Panda.DynamicWebApi.Attributes;
global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;