// <auto-generated />
using System;
using HaoKao.BurialPointService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.BurialPointService.Infrastructure.Migrations
{
    [DbContext(typeof(BurialPointDbContext))]
    [Migration("20240906015932_addInitdata")]
    partial class addInitdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.BurialPointService.Domain.Models.BrowseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BrowseData")
                        .HasColumnType("json")
                        .HasComment("浏览信息");

                    b.Property<Guid>("BurialPointId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("IsPaidUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("手机号");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("用户昵称");

                    b.HasKey("Id");

                    b.HasIndex("BurialPointId");

                    b.ToTable("BrowseRecord", (string)null);
                });

            modelBuilder.Entity("HaoKao.BurialPointService.Domain.Models.BurialPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BelongingPortType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("BurialPoint", (string)null);
                });

            modelBuilder.Entity("HaoKao.BurialPointService.Domain.Models.BrowseRecord", b =>
                {
                    b.HasOne("HaoKao.BurialPointService.Domain.Models.BurialPoint", null)
                        .WithMany("BrowseRecords")
                        .HasForeignKey("BurialPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.BurialPointService.Domain.Models.BurialPoint", b =>
                {
                    b.Navigation("BrowseRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
