// <auto-generated />
using System;
using HaoKao.CourseRatingService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.CourseRatingService.Infrastructure.Migrations
{
    [DbContext(typeof(CourseRatingRecordDbContext))]
    partial class CourseRatingRecordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.CourseRatingService.Domain.Models.CourseRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AuditState")
                        .HasColumnType("int")
                        .HasComment("审核状态");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasComment("头像");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasComment("评价内容");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)")
                        .HasComment("课程Id");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("课程名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("评价时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("评价人");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("昵称");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasComment("评价级别");

                    b.Property<bool>("Sticky")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否置顶");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("修改时间");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "CreatorId", "TenantId");

                    b.ToTable("CourseRating", (string)null);

                    b.HasComment("课程评价");
                });
#pragma warning restore 612, 618
        }
    }
}
