// <auto-generated />
using System;
using HaoKao.CorrectionNotebookService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaoKao.CorrectionNotebookService.Infrastructure.Migrations
{
    [DbContext(typeof(CorrectionNotebookDbContext))]
    partial class CorrectionNotebookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.ExamLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("创建人Id");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否内置数据");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("考试级别名称");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)")
                        .HasComment("父级Id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("CreatorId", "IsBuiltIn");

                    b.ToTable("ExamLevel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0190c3e6-3214-7dc6-bc25-6b0a5cab3d9e"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 1, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "经济师",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 2, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "初级经济师",
                            ParentId = new Guid("0190c3e6-3214-7dc6-bc25-6b0a5cab3d9e")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 3, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "中级经济师",
                            ParentId = new Guid("0190c3e6-3214-7dc6-bc25-6b0a5cab3d9e")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 4, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "高级经济师",
                            ParentId = new Guid("0190c3e6-3214-7dc6-bc25-6b0a5cab3d9e")
                        },
                        new
                        {
                            Id = new Guid("0190c3e6-3214-735b-8d36-7b41ccd9918a"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 5, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "会计师",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7d10-9754-339536267635"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 6, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "注册会计师",
                            ParentId = new Guid("0190c3e6-3214-735b-8d36-7b41ccd9918a")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7efd-8d62-8a061fe71b22"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 7, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "中级会计职称",
                            ParentId = new Guid("0190c3e6-3214-735b-8d36-7b41ccd9918a")
                        },
                        new
                        {
                            Id = new Guid("0190c3e6-3214-7b8b-b2ae-0d578805c176"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 8, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "社会工作者",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7cb5-9613-122673d29071"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 9, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "初级社会工作者",
                            ParentId = new Guid("0190c3e6-3214-7b8b-b2ae-0d578805c176")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7b3c-b30f-4626b1f94b76"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 10, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "中级社会工作者",
                            ParentId = new Guid("0190c3e6-3214-7b8b-b2ae-0d578805c176")
                        },
                        new
                        {
                            Id = new Guid("0190c3e6-3214-776a-9f19-5bd81cf0b8c0"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 11, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "计算机软件资格",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 12, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "软考中级职称",
                            ParentId = new Guid("0190c3e6-3214-776a-9f19-5bd81cf0b8c0")
                        },
                        new
                        {
                            Id = new Guid("0190c3e7-a245-7f93-ad52-3bc70bd9dcce"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 13, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "软考高级职称",
                            ParentId = new Guid("0190c3e6-3214-776a-9f19-5bd81cf0b8c0")
                        });
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.GenerationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("题目解析");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("题目答案");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("创建者Id");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("创建者名称");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)")
                        .HasComment("题目Id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "CreatorId");

                    b.ToTable("GenerationLog", (string)null);
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("题目解析");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("题目答案");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("题目内容(文本)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("创建人Id");

                    b.Property<Guid>("ExamLevelId")
                        .HasColumnType("char(36)")
                        .HasComment("考试级别Id");

                    b.Property<bool>("Generatable")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否可生成答案和解析");

                    b.Property<int>("GenerationTimes")
                        .HasColumnType("int")
                        .HasComment("生成次数");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("题目图片地址");

                    b.Property<int>("MasteryDegree")
                        .HasColumnType("int")
                        .HasComment("掌握程度");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("CreateTime", "CreatorId", "MasteryDegree");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("QuestionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("QuestionTag", (string)null);
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("创建人Id");

                    b.Property<Guid>("ExamLevelId")
                        .HasColumnType("char(36)")
                        .HasComment("考试级别Id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("科目图标");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否内置数据");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("科目名称");

                    b.HasKey("Id");

                    b.HasIndex("ExamLevelId");

                    b.HasIndex("CreatorId", "IsBuiltIn");

                    b.ToTable("Subject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0190c3ef-8743-71ce-968a-bb9140f63b3a"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E7%BB%8F%E6%B5%8E%E5%9F%BA%E7%A1%80%402x.png",
                            IsBuiltIn = true,
                            Name = "经济基础"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7bf8-abb8-737d392178ea"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E4%BA%BA%E5%8A%9B%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "人力资源管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-762e-8650-f21b638463b4"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%B7%A5%E5%95%86%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "工商管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7170-8305-8f0c4ec6710f"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E9%87%91%E8%9E%8D%402x.png",
                            IsBuiltIn = true,
                            Name = "金融"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7316-80b9-3943ab0f4964"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%BB%BA%E7%AD%91%E4%B8%8E%E6%88%BF%E5%9C%B0%E4%BA%A7%402x.png",
                            IsBuiltIn = true,
                            Name = "建筑与房地产经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7033-832f-f3e23ef3be39"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E7%9F%A5%E8%AF%86%E4%BA%A7%E6%9D%83%402x.png",
                            IsBuiltIn = true,
                            Name = "知识产权"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7d39-9a41-6a8f593fbaf8"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E8%B4%A2%E6%94%BF%E7%A8%8E%E6%94%B6%402x.png",
                            IsBuiltIn = true,
                            Name = "财政税收"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-79bf-8e03-4716c24dacd5"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E8%BF%90%E8%BE%93%E7%BB%8F%E6%B5%8E%402x.png",
                            IsBuiltIn = true,
                            Name = "运输经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7d1e-a683-0e4d8d0c2afa"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%86%9C%E4%B8%9A%E7%BB%8F%E6%B5%8E%402x.png",
                            IsBuiltIn = true,
                            Name = "农业经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7598-899a-2f0d0283f097"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E6%97%85%E6%B8%B8%402x.png",
                            IsBuiltIn = true,
                            Name = "旅游经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7b68-a903-3b525bfd3493"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7983-997a-1141082743be"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E4%BF%9D%E9%99%A9%402x.png",
                            IsBuiltIn = true,
                            Name = "保险"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7529-b37b-54200cf96680"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E7%BB%8F%E6%B5%8E%E5%9F%BA%E7%A1%80%402x.png",
                            IsBuiltIn = true,
                            Name = "经济基础"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-76d3-be78-dbbbbc64b9da"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E4%BA%BA%E5%8A%9B%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "人力资源管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7656-a6d8-eb98549cedb5"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%B7%A5%E5%95%86%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "工商管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-72b6-b702-b47b64eb8a04"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E9%87%91%E8%9E%8D%402x.png",
                            IsBuiltIn = true,
                            Name = "金融"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-76a6-8ce7-426d5e5e723f"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%BB%BA%E7%AD%91%E4%B8%8E%E6%88%BF%E5%9C%B0%E4%BA%A7%402x.png",
                            IsBuiltIn = true,
                            Name = "建筑与房地产经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7896-bbc5-bfa6493ccc9a"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E7%9F%A5%E8%AF%86%E4%BA%A7%E6%9D%83%402x.png",
                            IsBuiltIn = true,
                            Name = "知识产权"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7071-bb77-c3c115726963"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E8%B4%A2%E6%94%BF%E7%A8%8E%E6%94%B6%402x.png",
                            IsBuiltIn = true,
                            Name = "财政税收"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-72ff-bbb7-1e179ec221ba"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E8%BF%90%E8%BE%93%E7%BB%8F%E6%B5%8E%402x.png",
                            IsBuiltIn = true,
                            Name = "运输经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7713-a03d-061ba4f41c8a"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%86%9C%E4%B8%9A%E7%BB%8F%E6%B5%8E%402x.png",
                            IsBuiltIn = true,
                            Name = "农业经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7ec9-a5e4-0b49f9d39509"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E6%97%85%E6%B8%B8%402x.png",
                            IsBuiltIn = true,
                            Name = "旅游经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7dbc-b823-906196e0f02a"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7c1b-8630-a47ee4e91c09"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E4%BF%9D%E9%99%A9%402x.png",
                            IsBuiltIn = true,
                            Name = "保险"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7b4c-aa7f-5ffe2e771de3"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E4%BA%BA%E5%8A%9B%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "人力资源管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-792c-aa5b-cdb702201ebf"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%B7%A5%E5%95%86%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "工商管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7db1-b3d5-f308bedd33bb"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E9%87%91%E8%9E%8D%402x.png",
                            IsBuiltIn = true,
                            Name = "金融"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8743-7dd6-89a9-946d858a5700"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%BB%BA%E7%AD%91%E4%B8%8E%E6%88%BF%E5%9C%B0%E4%BA%A7%402x.png",
                            IsBuiltIn = true,
                            Name = "建筑与房地产经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7566-9fd5-8c07537131da"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E7%9F%A5%E8%AF%86%E4%BA%A7%E6%9D%83%402x.png",
                            IsBuiltIn = true,
                            Name = "知识产权"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7f81-bce2-4ae76d963b81"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E8%B4%A2%E6%94%BF%E7%A8%8E%E6%94%B6%402x.png",
                            IsBuiltIn = true,
                            Name = "财政税收"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7992-aa0c-e2e8efb7be8b"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E8%BF%90%E8%BE%93%E7%BB%8F%E6%B5%8E%402x.png",
                            IsBuiltIn = true,
                            Name = "运输经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7093-aacf-5178a34306f3"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E5%86%9C%E4%B8%9A%E7%BB%8F%E6%B5%8E%402x.png",
                            IsBuiltIn = true,
                            Name = "农业经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7da6-9939-cce429b59d47"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E6%97%85%E6%B8%B8%402x.png",
                            IsBuiltIn = true,
                            Name = "旅游经济"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7be0-8665-3cf3e4025b1c"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7fe3-ac55-f79166ebc5c9"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/jjs/%E4%BF%9D%E9%99%A9%402x.png",
                            IsBuiltIn = true,
                            Name = "保险"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7953-9b9e-036d64f9d722"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7d10-9754-339536267635"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E5%85%AC%E5%8F%B8%E6%88%98%E7%95%A5%E4%B8%8E%E9%A3%8E%E9%99%A9%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "公司战略与风险管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-777a-b985-0adeeb41e0cf"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7d10-9754-339536267635"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E7%BB%8F%E6%B5%8E%E6%B3%95%402x.png",
                            IsBuiltIn = true,
                            Name = "经济法"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7e4f-a046-352818453d75"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7d10-9754-339536267635"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E4%BC%9A%E8%AE%A1%402x.png",
                            IsBuiltIn = true,
                            Name = "会计"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7fde-9122-582cd15a8fda"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7d10-9754-339536267635"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E7%A8%8E%E6%B3%95%402x.png",
                            IsBuiltIn = true,
                            Name = "税法"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-799c-a00f-1764d9c593cc"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7d10-9754-339536267635"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E8%B4%A2%E5%8A%A1%E6%88%90%E6%9C%AC%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "财务成本管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7539-8d73-27d88bdda825"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7d10-9754-339536267635"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E5%AE%A1%E8%AE%A1%402x.png",
                            IsBuiltIn = true,
                            Name = "审计"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7c45-ab86-a8cede07a368"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7efd-8d62-8a061fe71b22"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E7%BB%8F%E6%B5%8E%E6%B3%95%E5%9F%BA%E7%A1%80%402x.png",
                            IsBuiltIn = true,
                            Name = "经济法"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7adb-b2f6-165be84e2549"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7efd-8d62-8a061fe71b22"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E8%B4%A2%E5%8A%A1%E7%AE%A1%E7%90%86%402x.png",
                            IsBuiltIn = true,
                            Name = "财务管理"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-79bf-869c-914549f73938"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7efd-8d62-8a061fe71b22"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/kj/%E4%BC%9A%E8%AE%A1%E5%AE%9E%E5%8A%A1%402x.png",
                            IsBuiltIn = true,
                            Name = "中级会计实务"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-721c-9f39-fdd3b2581276"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7cb5-9613-122673d29071"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/sg/%E7%A4%BE%E4%BC%9A%E5%B7%A5%E4%BD%9C%E5%AE%9E%E5%8A%A1%402x.png",
                            IsBuiltIn = true,
                            Name = "社会工作实务"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-76b3-b54f-79dff76044b4"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7cb5-9613-122673d29071"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/sg/%E7%A4%BE%E4%BC%9A%E5%B7%A5%E4%BD%9C%E7%BB%BC%E5%90%88%E8%83%BD%E5%8A%9B%402x.png",
                            IsBuiltIn = true,
                            Name = "社会工作综合能力"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7f14-8aec-9a55efe68c2f"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7b3c-b30f-4626b1f94b76"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/sg/%E7%A4%BE%E4%BC%9A%E5%B7%A5%E4%BD%9C%E5%AE%9E%E5%8A%A1%402x.png",
                            IsBuiltIn = true,
                            Name = "社会工作实务"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7805-8748-b1a7d4bb554b"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7b3c-b30f-4626b1f94b76"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/sg/%E7%A4%BE%E4%BC%9A%E5%B7%A5%E4%BD%9C%E6%B3%95%E8%A7%84%E4%B8%8E%E6%94%BF%E7%AD%96%402x.png",
                            IsBuiltIn = true,
                            Name = "社会工作法规与政策"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-74f3-b994-f6e9c30b86a7"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7b3c-b30f-4626b1f94b76"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/sg/%E7%A4%BE%E4%BC%9A%E5%B7%A5%E4%BD%9C%E7%BB%BC%E5%90%88%E8%83%BD%E5%8A%9B%402x.png",
                            IsBuiltIn = true,
                            Name = "社会工作综合能力"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7bbe-a6e7-d3eabac9e5c3"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86%E5%B7%A5%E7%A8%8B%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "系统集成项目管理工程师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-75e7-b691-7db6e6f67170"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E8%BD%AF%E4%BB%B6%E8%AE%BE%E8%AE%A1%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "软件设计师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7930-86f6-6afbf0b1e5e9"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B3%BB%E7%BB%9F%E5%B7%A5%E7%A8%8B%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "数据库系统工程师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7164-8c80-bbd332272481"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E7%94%B5%E5%AD%90%E5%95%86%E5%8A%A1%E8%AE%BE%E8%AE%A1%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "电子商务设计师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-73d8-963f-8f0535f7f43c"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E7%BD%91%E7%BB%9C%E5%B7%A5%E7%A8%8B%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "网络工程师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7e71-a99b-1b31d3ccbf0c"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E4%BF%A1%E6%81%AF%E5%AE%89%E5%85%A8%E5%B7%A5%E7%A8%8B%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "信息安全工程师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7263-a310-8aa4054d75e2"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E4%BF%A1%E6%81%AF%E7%B3%BB%E7%BB%9F%E7%9B%91%E7%90%86%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "信息系统监理师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7f15-be59-7c9aa57db72d"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E4%BF%A1%E6%81%AF%E7%B3%BB%E7%BB%9F%E7%AE%A1%E7%90%86%E5%B7%A5%E7%A8%8B%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "信息系统管理工程师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-732a-81a4-b368da5f182c"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-71ce-ba7d-6c26e155cc17"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E8%BD%AF%E4%BB%B6%E8%AF%84%E6%B5%8B%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "软件评测师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-79f6-98d1-fa17543852f0"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7f93-ad52-3bc70bd9dcce"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E4%BF%A1%E6%81%AF%E7%B3%BB%E7%BB%9F%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "信息系统项目管理师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-73e5-94cd-8fcacb2d3f54"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7f93-ad52-3bc70bd9dcce"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E7%B3%BB%E7%BB%9F%E5%88%86%E6%9E%90%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "系统分析师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8744-7c93-870a-bd345d0d9850"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7f93-ad52-3bc70bd9dcce"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E7%BD%91%E7%BB%9C%E8%A7%84%E8%AE%BE%E8%AE%A1%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "网络规划设计师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8745-747f-8e86-91784dcde76f"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7f93-ad52-3bc70bd9dcce"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E7%B3%BB%E7%BB%9F%E8%A7%84%E5%88%92%E4%B8%8E%E7%AE%A1%E7%90%86%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "系统规划与管理师"
                        },
                        new
                        {
                            Id = new Guid("0190c3ef-8745-783a-b8ed-f68787eeff35"),
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExamLevelId = new Guid("0190c3e7-a245-7f93-ad52-3bc70bd9dcce"),
                            Icon = "https://new-haokao.oss-cn-shenzhen.aliyuncs.com/CorrectionNotebook/rk/%E7%B3%BB%E7%BB%9F%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1%E5%B8%88%402x.png",
                            IsBuiltIn = true,
                            Name = "系统架构师"
                        });
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.SubjectSort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("创建人Id");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否内置数据");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("CreatorId", "SubjectId");

                    b.ToTable("SubjectSort", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7b50-8af2-facbba282958"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8743-71ce-968a-bb9140f63b3a")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7065-8ceb-4391642e4644"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8743-7bf8-abb8-737d392178ea")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7573-a642-80193a552399"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8743-762e-8650-f21b638463b4")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-743b-b266-647862085453"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 4,
                            SubjectId = new Guid("0190c3ef-8743-7170-8305-8f0c4ec6710f")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7b47-91b2-14cee948c838"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 5,
                            SubjectId = new Guid("0190c3ef-8743-7316-80b9-3943ab0f4964")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7808-95ab-2c84298ce396"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 6,
                            SubjectId = new Guid("0190c3ef-8743-7033-832f-f3e23ef3be39")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-783f-9ccf-4f2586e3bc58"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 7,
                            SubjectId = new Guid("0190c3ef-8743-7d39-9a41-6a8f593fbaf8")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-782a-a835-a3c3073874c0"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 8,
                            SubjectId = new Guid("0190c3ef-8743-79bf-8e03-4716c24dacd5")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7d13-bc87-331c5d8703f0"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 9,
                            SubjectId = new Guid("0190c3ef-8743-7d1e-a683-0e4d8d0c2afa")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-72bf-8a4f-1f87045b5d04"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 10,
                            SubjectId = new Guid("0190c3ef-8743-7598-899a-2f0d0283f097")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-79cf-92cc-6eb720470724"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 11,
                            SubjectId = new Guid("0190c3ef-8743-7b68-a903-3b525bfd3493")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7d10-8d81-40defafa7d3b"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8743-7529-b37b-54200cf96680")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7109-be8c-5194444d7617"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8743-76d3-be78-dbbbbc64b9da")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7e6d-98c7-f8241d96ac44"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8743-7656-a6d8-eb98549cedb5")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7928-a2c0-1e454f1b3426"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 4,
                            SubjectId = new Guid("0190c3ef-8743-72b6-b702-b47b64eb8a04")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-71b7-b1ac-916c5244bc76"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 5,
                            SubjectId = new Guid("0190c3ef-8743-76a6-8ce7-426d5e5e723f")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-72d0-b2af-1b12098ffb06"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 6,
                            SubjectId = new Guid("0190c3ef-8743-7896-bbc5-bfa6493ccc9a")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7301-ada3-fcefc48bfcd4"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 7,
                            SubjectId = new Guid("0190c3ef-8743-7071-bb77-c3c115726963")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-78c8-b51d-68ec0bbf8336"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 8,
                            SubjectId = new Guid("0190c3ef-8743-72ff-bbb7-1e179ec221ba")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7827-a73a-33bdcff42b25"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 9,
                            SubjectId = new Guid("0190c3ef-8743-7713-a03d-061ba4f41c8a")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-73bc-b9b9-cd4f459cb77e"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 10,
                            SubjectId = new Guid("0190c3ef-8743-7ec9-a5e4-0b49f9d39509")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-73a7-af2d-9d42b8c79951"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 11,
                            SubjectId = new Guid("0190c3ef-8743-7dbc-b823-906196e0f02a")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7ebd-9f42-4278026948cd"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8743-7b4c-aa7f-5ffe2e771de3")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7005-b5fd-17475dc6fa10"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8743-792c-aa5b-cdb702201ebf")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7c98-b5a9-8aa9aa3eba15"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8743-7db1-b3d5-f308bedd33bb")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7e83-b2b1-ca7d6164768a"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 4,
                            SubjectId = new Guid("0190c3ef-8743-7dd6-89a9-946d858a5700")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-71f8-8ca5-8edf01cadf27"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 5,
                            SubjectId = new Guid("0190c3ef-8744-7566-9fd5-8c07537131da")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-79c9-83fd-b778c6aca4c2"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 6,
                            SubjectId = new Guid("0190c3ef-8744-7f81-bce2-4ae76d963b81")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-776b-8c42-a3dcf2887f3f"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 7,
                            SubjectId = new Guid("0190c3ef-8744-7992-aa0c-e2e8efb7be8b")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7b87-b099-5c44eb3f26f3"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 8,
                            SubjectId = new Guid("0190c3ef-8744-7093-aacf-5178a34306f3")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c44-7551-9dc1-94709d479d7b"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 9,
                            SubjectId = new Guid("0190c3ef-8744-7da6-9939-cce429b59d47")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7357-8866-5d4ccc6ec2a6"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 10,
                            SubjectId = new Guid("0190c3ef-8744-7be0-8665-3cf3e4025b1c")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7427-a87f-8cceb68e1bad"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8744-7953-9b9e-036d64f9d722")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-72ad-bda2-cef3016b8c46"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8744-777a-b985-0adeeb41e0cf")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-72f6-bda1-a3be237469b0"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8744-7e4f-a046-352818453d75")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7ff1-8efe-b87c2f7b72f0"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 4,
                            SubjectId = new Guid("0190c3ef-8744-7fde-9122-582cd15a8fda")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-715e-a5a6-dae02cf42571"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 5,
                            SubjectId = new Guid("0190c3ef-8744-799c-a00f-1764d9c593cc")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7853-8682-a99091882d94"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 6,
                            SubjectId = new Guid("0190c3ef-8744-7539-8d73-27d88bdda825")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-711e-904d-e3e3cd98a053"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8744-7c45-ab86-a8cede07a368")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-78f8-b4e9-c23e59c00b38"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8744-7adb-b2f6-165be84e2549")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-712d-a6b1-2bd194e1ea01"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8744-79bf-869c-914549f73938")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7e08-b3ca-b9ca1d016483"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8744-721c-9f39-fdd3b2581276")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7386-bf89-3165cad1cfaa"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8744-76b3-b54f-79dff76044b4")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-78e7-a0c3-72ed0756fdc5"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8744-7f14-8aec-9a55efe68c2f")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-79a9-b73f-630e96eb52f9"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8744-7805-8748-b1a7d4bb554b")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7774-a130-c28f2775fea8"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8744-74f3-b994-f6e9c30b86a7")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-77cc-96d9-e1525db6eeba"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8744-7bbe-a6e7-d3eabac9e5c3")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-736c-8026-4bc5d657194f"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8744-75e7-b691-7db6e6f67170")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7b3d-af06-7aab27a0fbcc"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8744-7930-86f6-6afbf0b1e5e9")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7346-a26b-70123f5e67e2"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 4,
                            SubjectId = new Guid("0190c3ef-8744-7164-8c80-bbd332272481")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7a8c-9466-ac1c7dde0c82"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 5,
                            SubjectId = new Guid("0190c3ef-8744-73d8-963f-8f0535f7f43c")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-70aa-8421-4ece42785e76"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 6,
                            SubjectId = new Guid("0190c3ef-8744-7e71-a99b-1b31d3ccbf0c")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-74f4-8436-871e3eb22072"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 7,
                            SubjectId = new Guid("0190c3ef-8744-7263-a310-8aa4054d75e2")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7e1f-aae8-41718b5a67fa"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 8,
                            SubjectId = new Guid("0190c3ef-8744-7f15-be59-7c9aa57db72d")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-71fb-a47e-243da0cf1940"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 9,
                            SubjectId = new Guid("0190c3ef-8744-732a-81a4-b368da5f182c")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-788c-ae35-ba0197e0e35c"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 1,
                            SubjectId = new Guid("0190c3ef-8744-79f6-98d1-fa17543852f0")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-773a-a605-d073e7f4f0a2"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 2,
                            SubjectId = new Guid("0190c3ef-8744-73e5-94cd-8fcacb2d3f54")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7fd9-a220-c768f0ba99d1"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 3,
                            SubjectId = new Guid("0190c3ef-8744-7c93-870a-bd345d0d9850")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7f04-ae8a-5d16bb2b85b8"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 4,
                            SubjectId = new Guid("0190c3ef-8745-747f-8e86-91784dcde76f")
                        },
                        new
                        {
                            Id = new Guid("0190ca74-1c45-7e00-b18f-7aefbcbe2f2a"),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Priority = 5,
                            SubjectId = new Guid("0190c3ef-8745-783a-b8ed-f68787eeff35")
                        });
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("标签分类");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("创建人Id");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否内置数据");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("标签名称");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-70ed-b554-cab99cf71a2b"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 1, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "单选题"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7f7d-97a8-e6f31310ea90"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 2, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "多选题"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7c19-ae1a-e069e46dad5a"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 3, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "不定项选择题"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7c03-af63-0482f1f8177b"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 4, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "判断题"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-74cb-95fa-2204eb2217b1"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 5, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "填空题"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-76d4-92a6-5e2ee9b06a97"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 6, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "案例分析题"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-76c4-95dc-b85db92445d8"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 7, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "问答题"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-77a1-ba5c-6ea1e2d0d06b"),
                            Category = "题型",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 8, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "其他"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7927-8b80-e5c337fba29e"),
                            Category = "难易程度",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 9, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "简单"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7d4d-aef5-a7e00f35c5bb"),
                            Category = "难易程度",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 10, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "一般"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-70b6-a3c9-7ea275f314a7"),
                            Category = "难易程度",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 11, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "比较难"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7a1c-9f34-6449080abdf3"),
                            Category = "难易程度",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 12, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "非常难"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7d33-87eb-fc7fdee7df7c"),
                            Category = "错误原因",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 13, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "马虎粗心"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7e98-84f5-c0cfbf5e27d1"),
                            Category = "错误原因",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 14, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "概念未掌握"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-776d-8ecb-684b43b395c7"),
                            Category = "错误原因",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 15, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "没有思路"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-7e34-8775-33f1dfa66fb7"),
                            Category = "错误原因",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 16, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "运算错误"
                        },
                        new
                        {
                            Id = new Guid("0190fd34-7e0c-76b0-ad52-3b531e8a7756"),
                            Category = "错误原因",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 17, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsBuiltIn = true,
                            Name = "其他"
                        });
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.GenerationLog", b =>
                {
                    b.HasOne("HaoKao.CorrectionNotebookService.Domain.Entities.Question", null)
                        .WithMany("GenerationLogs")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Question", b =>
                {
                    b.HasOne("HaoKao.CorrectionNotebookService.Domain.Entities.Subject", null)
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.QuestionTag", b =>
                {
                    b.HasOne("HaoKao.CorrectionNotebookService.Domain.Entities.Question", "Question")
                        .WithMany("Tags")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaoKao.CorrectionNotebookService.Domain.Entities.Tag", "Tag")
                        .WithMany("QuestionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Subject", b =>
                {
                    b.HasOne("HaoKao.CorrectionNotebookService.Domain.Entities.ExamLevel", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ExamLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.SubjectSort", b =>
                {
                    b.HasOne("HaoKao.CorrectionNotebookService.Domain.Entities.Subject", null)
                        .WithMany("Sorts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.ExamLevel", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Question", b =>
                {
                    b.Navigation("GenerationLogs");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Sorts");
                });

            modelBuilder.Entity("HaoKao.CorrectionNotebookService.Domain.Entities.Tag", b =>
                {
                    b.Navigation("QuestionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
