// <auto-generated />
using System;
using HaoKao.KnowledgePointService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaoKao.KnowledgePointService.Infrastructure.Migrations
{
    [DbContext(typeof(KnowledgePointDbContext))]
    partial class KnowledgePointDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.KnowledgePointService.Domain.Entities.KnowledgePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChapterNodeId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("章节Id");

                    b.Property<string>("ChapterNodeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasComment("章节名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasComment("知识点名称");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterNodeId", "Name", "TenantId");

                    b.ToTable("KnowledgePoint", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
