// <auto-generated />
using System;
using HaoKao.UserAnswerRecordService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.UserAnswerRecordService.Infrastructure.Migrations
{
    [DbContext(typeof(UserAnswerRecordDbContext))]
    [Migration("20250721070547_InitNewAnswerRecord")]
    partial class InitNewAnswerRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("答题时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("用户Id");

                    b.Property<int>("JudgeResult")
                        .HasColumnType("int")
                        .HasComment("判题结果");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasComment("试题父Id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)")
                        .HasComment("试题Id");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("char(36)")
                        .HasComment("试题类型Id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("char(36)")
                        .HasComment("作答记录Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<string>("UserAnswers")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasComment("用户作答");

                    b.Property<bool>("WhetherMark")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否标记");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.HasIndex("QuestionId", "CreatorId", "CreateTime", "TenantId");

                    b.ToTable("AnswerQuestion", null, t =>
                        {
                            t.HasComment("作答试题");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AnswerCount")
                        .HasColumnType("int")
                        .HasComment("答题数量");

                    b.Property<int>("AnswerType")
                        .HasColumnType("int");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int")
                        .HasComment("正确数量");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("答题时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("用户Id");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint")
                        .HasComment("答题时间");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int")
                        .HasComment("题目数量");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "CreatorId", "TenantId");

                    b.ToTable("AnswerRecord", null, t =>
                        {
                            t.HasComment("作答记录");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.ChapterAnswerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnswerRecordId")
                        .HasColumnType("char(36)")
                        .HasComment("作答记录Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasComment("分类Id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("char(36)")
                        .HasComment("章节Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("答题时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("用户Id");

                    b.Property<Guid>("KnowledgePointId")
                        .HasColumnType("char(36)")
                        .HasComment("知识点Id");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("char(36)")
                        .HasComment("小节Id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.HasIndex("AnswerRecordId")
                        .IsUnique();

                    b.HasIndex("KnowledgePointId", "CreatorId", "CategoryId", "TenantId");

                    b.HasIndex("SectionId", "CreatorId", "CategoryId", "TenantId");

                    b.HasIndex("SubjectId", "CreatorId", "CategoryId", "TenantId");

                    b.HasIndex("KnowledgePointId", "SectionId", "ChapterId", "SubjectId", "CreatorId", "CategoryId", "TenantId");

                    b.ToTable("ChapterAnswerRecord", null, t =>
                        {
                            t.HasComment("章节知识点作答记录");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.DateAnswerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnswerRecordId")
                        .HasColumnType("char(36)")
                        .HasComment("答题记录Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("答题时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("用户Id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasComment("日期");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("类型");

                    b.HasKey("Id");

                    b.HasIndex("AnswerRecordId")
                        .IsUnique();

                    b.HasIndex("Date", "SubjectId", "Type", "CreatorId", "TenantId")
                        .IsUnique();

                    b.ToTable("DateAnswerRecord", null, t =>
                        {
                            t.HasComment("日期相关作答记录");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.PaperAnswerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnswerRecordId")
                        .HasColumnType("char(36)")
                        .HasComment("答题记录Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasComment("类别Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("答题时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("用户Id");

                    b.Property<Guid>("PaperId")
                        .HasColumnType("char(36)")
                        .HasComment("试卷Id");

                    b.Property<decimal>("PassingScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasComment("及格分");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("学科Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasComment("总分");

                    b.Property<decimal>("UserScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasComment("用户得分");

                    b.HasKey("Id");

                    b.HasIndex("AnswerRecordId")
                        .IsUnique();

                    b.HasIndex("PaperId", "SubjectId", "CreatorId", "CategoryId", "TenantId");

                    b.ToTable("PaperAnswerRecord", null, t =>
                        {
                            t.HasComment("试卷作答记录");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UnionAnswerQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("JudgeResult")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("UnionAnswerRecordId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UnionAnswerRecordId");

                    b.HasIndex("QuestionId", "TenantId");

                    b.ToTable("UnionAnswerQuestion", (string)null);
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UnionAnswerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("QuestionCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RecordIdentifier")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("SubjectId", "QuestionCategoryId", "CreatorId", "TenantId");

                    b.ToTable("UnionAnswerRecord", (string)null);
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UserAnswerQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("JudgeResult")
                        .HasColumnType("int")
                        .HasComment("判题结果");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasComment("父题目Id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)")
                        .HasComment("试题Id");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<Guid>("UserAnswerRecordId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("UserScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasComment("用户得分");

                    b.Property<bool>("WhetherMark")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UserAnswerRecordId");

                    b.HasIndex("QuestionId", "TenantId");

                    b.ToTable("UserAnswerQuestion_2025", null, t =>
                        {
                            t.HasComment("答题记录试题表");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UserAnswerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AnswerCount")
                        .HasColumnType("int")
                        .HasComment("作答数");

                    b.Property<int>("AnswerType")
                        .HasColumnType("int")
                        .HasComment("答题类型");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int")
                        .HasComment("正确数");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("用户Id");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint")
                        .HasComment("耗时");

                    b.Property<decimal>("PassingScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasComment("及格分数");

                    b.Property<Guid>("QuestionCategoryId")
                        .HasColumnType("char(36)")
                        .HasComment("分类Id");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int")
                        .HasComment("总题数");

                    b.Property<Guid>("RecordIdentifier")
                        .HasColumnType("char(36)")
                        .HasComment("答题标识符 章节Id，或试卷Id，每日一练为Guid.Empty");

                    b.Property<string>("RecordIdentifierName")
                        .HasColumnType("varchar(100)")
                        .HasComment("答题标识符名称");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasComment("试题总分");

                    b.Property<decimal>("UserScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasComment("用户得分");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "QuestionCategoryId", "RecordIdentifier", "CreatorId", "CreateTime", "TenantId");

                    b.ToTable("UserAnswerRecord_2025", null, t =>
                        {
                            t.HasComment("答题记录");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UserQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("OptionContent")
                        .HasColumnType("text")
                        .HasComment("回答内容");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("char(36)")
                        .HasComment("选项Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid?>("UserAnswerQuestionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserAnswerQuestionId");

                    b.ToTable("UserQuestionOption_2025", null, t =>
                        {
                            t.HasComment("用户答题的选项或内容");
                        });
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerQuestion", b =>
                {
                    b.HasOne("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerRecord", null)
                        .WithMany("Questions")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.ChapterAnswerRecord", b =>
                {
                    b.HasOne("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerRecord", "AnswerRecord")
                        .WithOne()
                        .HasForeignKey("HaoKao.UserAnswerRecordService.Domain.Entities.ChapterAnswerRecord", "AnswerRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerRecord");
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.DateAnswerRecord", b =>
                {
                    b.HasOne("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerRecord", "AnswerRecord")
                        .WithOne()
                        .HasForeignKey("HaoKao.UserAnswerRecordService.Domain.Entities.DateAnswerRecord", "AnswerRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerRecord");
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.PaperAnswerRecord", b =>
                {
                    b.HasOne("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerRecord", "AnswerRecord")
                        .WithOne()
                        .HasForeignKey("HaoKao.UserAnswerRecordService.Domain.Entities.PaperAnswerRecord", "AnswerRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerRecord");
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UnionAnswerQuestion", b =>
                {
                    b.HasOne("HaoKao.UserAnswerRecordService.Domain.Entities.UnionAnswerRecord", null)
                        .WithMany()
                        .HasForeignKey("UnionAnswerRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UserAnswerQuestion", b =>
                {
                    b.HasOne("HaoKao.UserAnswerRecordService.Domain.Entities.UserAnswerRecord", null)
                        .WithMany("RecordQuestions")
                        .HasForeignKey("UserAnswerRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UserQuestionOption", b =>
                {
                    b.HasOne("HaoKao.UserAnswerRecordService.Domain.Entities.UserAnswerQuestion", null)
                        .WithMany("QuestionOptions")
                        .HasForeignKey("UserAnswerQuestionId");
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.AnswerRecord", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UserAnswerQuestion", b =>
                {
                    b.Navigation("QuestionOptions");
                });

            modelBuilder.Entity("HaoKao.UserAnswerRecordService.Domain.Entities.UserAnswerRecord", b =>
                {
                    b.Navigation("RecordQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
