// <auto-generated />
using System;
using HaoKao.DrawPrizeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.DrawPrizeService.Infrastructure.Migrations
{
    [DbContext(typeof(DrawPrizeDbContext))]
    [Migration("20240711032705_AllowEmpty")]
    partial class AllowEmpty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.DrawPrizeService.Domain.Models.DrawPrize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasComment("活动背景图");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Desc")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar")
                        .HasComment("说明");

                    b.Property<int?>("DrawPrizeRange")
                        .HasColumnType("int");

                    b.Property<int?>("DrawPrizeType")
                        .HasColumnType("int");

                    b.Property<string>("DrawPrizeUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasComment("抽奖链接");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasComment("结束时间");

                    b.Property<double?>("Probability")
                        .HasColumnType("double");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasComment("开始时间");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("名称");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DrawPrizeType");

                    b.ToTable("DrawPrize", (string)null);
                });

            modelBuilder.Entity("HaoKao.DrawPrizeService.Domain.Models.DrawPrizeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("DrawPrizeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("手机号");

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PrizeName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("奖品名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("DrawPrizeId");

                    b.ToTable("DrawPrizeRecord", (string)null);
                });

            modelBuilder.Entity("HaoKao.DrawPrizeService.Domain.Models.Prize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AwardedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DesignatedStudents")
                        .HasColumnType("json")
                        .HasComment("指定学员");

                    b.Property<int>("DisplayCount")
                        .HasColumnType("int");

                    b.Property<Guid>("DrawPrizeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsGuaranteed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Version"));

                    b.Property<int>("WinningRange")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawPrizeId");

                    b.ToTable("Prize", (string)null);
                });

            modelBuilder.Entity("HaoKao.DrawPrizeService.Domain.Models.DrawPrizeRecord", b =>
                {
                    b.HasOne("HaoKao.DrawPrizeService.Domain.Models.DrawPrize", "DrawPrize")
                        .WithMany("DrawPrizeRecords")
                        .HasForeignKey("DrawPrizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawPrize");
                });

            modelBuilder.Entity("HaoKao.DrawPrizeService.Domain.Models.Prize", b =>
                {
                    b.HasOne("HaoKao.DrawPrizeService.Domain.Models.DrawPrize", "DrawPrize")
                        .WithMany("Prizes")
                        .HasForeignKey("DrawPrizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawPrize");
                });

            modelBuilder.Entity("HaoKao.DrawPrizeService.Domain.Models.DrawPrize", b =>
                {
                    b.Navigation("DrawPrizeRecords");

                    b.Navigation("Prizes");
                });
#pragma warning restore 612, 618
        }
    }
}
