// <auto-generated />
using System;
using HaoKao.StudyMaterialService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.StudyMaterialService.Infrastructure.Migrations
{
    [DbContext(typeof(StudyMaterialDbContext))]
    partial class StudyMaterialRecordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.StudyMaterialService.Domain.Models.StudyMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("创建人");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)")
                        .HasComment("启用/禁用");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasComment("资料内容");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("资料名称");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("科目");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("修改时间");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasComment("年份");

                    b.HasKey("Id");

                    b.ToTable("StudyMaterial", (string)null);

                    b.HasComment("学习资料");
                });
#pragma warning restore 612, 618
        }
    }
}
