// <auto-generated />
using System;
using HaoKao.CourseService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.CourseService.Infrastructure.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20230726014255_addvideostoragetable1")]
    partial class addvideostoragetable1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.CourseService.Domain.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("课程名称");

                    b.Property<bool>("State")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("科目名称");

                    b.Property<string>("TeacherJson")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasComment("主讲老师json");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UpdateTimeDesc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("预计更新时间");

                    b.Property<string>("Year")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("年份");

                    b.HasKey("Id");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.Models.CourseChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("名称");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("CourseChapter", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.Models.CourseMaterials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseChapterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("讲义地址");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("讲义名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("CourseMaterials", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.Models.CourseVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseChapterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsTry")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("KnowledgePointId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("SourceName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("视频源名称");

                    b.Property<string>("Suffix")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("后缀");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("视频id");

                    b.Property<string>("VideoName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("视频名称");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("播放url-冗余");

                    b.HasKey("Id");

                    b.ToTable("CourseVideo", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.Models.VideoStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigParameter")
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)")
                        .HasComment("视频存储器相关的配置");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("VideoStorageHandlerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("VideoStorageHandlerName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("视频存储器名称");

                    b.HasKey("Id");

                    b.ToTable("VideoStorage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
