// <auto-generated />
using System;
using HaoKao.CourseService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.CourseService.Infrastructure.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20250625030320_addSmartAssistanceAttribute")]
    partial class addSmartAssistanceAttribute
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.CourseService.Domain.Course.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseMaterialsPackageName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("课程讲义包名称");

                    b.Property<string>("CourseMaterialsPackageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("课程讲义包url");

                    b.Property<int>("CourseType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("课程名称");

                    b.Property<bool>("State")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("科目名称");

                    b.Property<string>("TeacherJson")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar")
                        .HasComment("主讲老师json");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UpdateTimeDesc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("预计更新时间");

                    b.Property<string>("Year")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("年份");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Name", "SubjectId", "State", "TenantId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.CourseChapter.CourseChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("名称");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "TenantId");

                    b.ToTable("CourseChapter", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.CourseMaterials.CourseMaterials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseChapterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("讲义地址");

                    b.Property<Guid?>("KnowledgePointId")
                        .HasColumnType("char(36)");

                    b.Property<string>("KnowledgePointName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("关联的知识点名称");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("讲义名称");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CourseChapterId", "TenantId");

                    b.ToTable("CourseMaterials", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.CoursePractice.CoursePractice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChapterNodeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChapterNodeName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("试题章节名称");

                    b.Property<Guid>("CourseChapterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseChapterName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("课程章节名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("KnowledgePointId")
                        .HasColumnType("char(36)");

                    b.Property<string>("KnowledgePointName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("关联的知识点名称");

                    b.Property<Guid?>("QuestionCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("QuestionCategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("试题分类名称");

                    b.Property<string>("QuestionIds")
                        .HasColumnType("json")
                        .HasComment("试题id集合(智辅学习课程，添加课后练习使用)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CourseChapterId")
                        .IsUnique();

                    b.ToTable("CoursePractice", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.CourseVideo.CourseVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long?>("CateId")
                        .HasColumnType("bigint");

                    b.Property<string>("CateName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("视频分类名称");

                    b.Property<Guid>("CourseChapterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("显示名称");

                    b.Property<decimal>("Duration")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("时长");

                    b.Property<bool>("IsTry")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("KnowledgePointId")
                        .HasColumnType("char(36)");

                    b.Property<string>("KnowledgePointIds")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar")
                        .HasComment("知识点");

                    b.Property<string>("KnowledgePointName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("关联的知识点名称");

                    b.Property<string>("QzName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("前缀名称");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("SourceName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("视频源名称");

                    b.Property<string>("Suffix")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("后缀");

                    b.Property<string>("Tags")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasComment("视频标签");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("视频id");

                    b.Property<string>("VideoName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("视频名称");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("播放url-冗余");

                    b.HasKey("Id");

                    b.HasIndex("CourseChapterId", "TenantId");

                    b.ToTable("CourseVideo", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.CourseVideoNote.CourseVideoNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CourseVideoNoteType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("创建者名称");

                    b.Property<string>("NoteContent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("笔记内容");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<decimal>("TimeNode")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("视频时间节点");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("视频id");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "CreatorId");

                    b.ToTable("CourseVideoNote", (string)null);
                });

            modelBuilder.Entity("HaoKao.CourseService.Domain.VideoStorage.VideoStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigParameter")
                        .HasMaxLength(800)
                        .HasColumnType("varchar")
                        .HasComment("视频存储器相关的配置");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("VideoStorageHandlerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("VideoStorageHandlerName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("视频存储器名称");

                    b.HasKey("Id");

                    b.ToTable("VideoStorage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
