// <auto-generated />
using System;
using HaoKao.LecturerService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.LecturerService.Infrastructure.Migrations
{
    [DbContext(typeof(LecturerDbContext))]
    partial class LecturerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.LecturerService.Domain.Models.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseIntroduction")
                        .HasColumnType("text")
                        .HasComment("课程介绍");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Desc")
                        .HasColumnType("text")
                        .HasComment("简介");

                    b.Property<string>("HeadPortraitUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("头像");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("教师姓名");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("形象照");

                    b.Property<string>("ProductPackageIds")
                        .HasColumnType("json")
                        .HasComment("关联的产品包Id");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("SubjectIds")
                        .HasColumnType("json")
                        .HasComment("科目Id数组");

                    b.Property<string>("SubjectNames")
                        .HasColumnType("json")
                        .HasComment("科目名称数组");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Name", "TenantId");

                    b.ToTable("Lecturer", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
