// <auto-generated />
using System;
using HaoKao.SubjectService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaoKao.SubjectService.Infrastructure.Migrations
{
    [DbContext(typeof(SubjectDbContext))]
    [Migration("20230630012458_innitdatabase20230630")]
    partial class innitdatabase20230630
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.SubjectService.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("IsCommon")
                        .HasColumnType("int")
                        .HasComment("是否是专业科目");

                    b.Property<bool>("IsShow")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("科目名称");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TrialSubjectId")
                        .HasColumnType("varchar(50)")
                        .HasComment("命审题科目Id");

                    b.HasKey("Id");

                    b.HasIndex("Name", "TenantId");

                    b.ToTable("Subject", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
