// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.StudentService.Infrastructure.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20231009035842_addStudentParameterConfig")]
    partial class addStudentParameterConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.StudentService.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("邮箱");

                    b.Property<int>("IsFirst")
                        .HasColumnType("int");

                    b.Property<bool>("IsOldStudent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("昵称");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("手机号码");

                    b.Property<int>("StudyBase")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TenantName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("租户名称");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Phone", "NickName", "TenantId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("HaoKao.StudentService.Domain.Models.StudentParameterConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Desc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasComment("描述");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("昵称");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("设置值字段名称");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("设置值类型");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("设置值");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TenantName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PropertyName");

                    b.ToTable("StudentParameterConfig", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
