// <auto-generated />
using System;
using HaoKao.WebsiteConfigurationService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.WebsiteConfigurationService.Infrastructure.Migrations
{
    [DbContext(typeof(WebsiteConfigurationDbContext))]
    [Migration("20230911090738_addIndex")]
    partial class addIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.WebsiteConfigurationService.Domain.Models.Column", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveIcon")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("当前图标");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("别名");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DomainName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("域名");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("英文名");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("图标");

                    b.Property<bool>("IsHomePage")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("名称");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("EnglishName", "DomainName", "TenantId");

                    b.ToTable("Column", (string)null);
                });

            modelBuilder.Entity("HaoKao.WebsiteConfigurationService.Domain.Models.TemplateStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DomainName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("域名");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("名称");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("内容");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DomainName", "TenantId");

                    b.ToTable("TemplateStyle", (string)null);
                });

            modelBuilder.Entity("HaoKao.WebsiteConfigurationService.Domain.Models.WebsiteTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ColumnName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("所属栏目名称");

                    b.Property<string>("Content")
                        .HasColumnType("mediumtext")
                        .HasComment("内容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Desc")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("描述");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.Property<long>("WebsiteTemplateType")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId", "TenantId");

                    b.ToTable("WebsiteTemplate", (string)null);
                });

            modelBuilder.Entity("HaoKao.WebsiteConfigurationService.Domain.Models.Column", b =>
                {
                    b.HasOne("HaoKao.WebsiteConfigurationService.Domain.Models.Column", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("HaoKao.WebsiteConfigurationService.Domain.Models.Column", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
