// <auto-generated />
using System;
using HaoKao.DeepSeekService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.DeepSeekService.Infrastructure.Migrations
{
    [DbContext(typeof(DeepSeekDbContext))]
    [Migration("20250718072539_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.DeepSeekService.Domain.DeepSeekConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("Api密钥");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("接口地址");

                    b.Property<decimal?>("FrequencyPenalty")
                        .HasColumnType("decimal(6, 2)")
                        .HasComment("重复内容的可能性");

                    b.Property<bool?>("Logprobs")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否返回所输出 token 的对数概率");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("int")
                        .HasComment("最大Token");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("模型");

                    b.Property<decimal?>("PresencePenalty")
                        .HasColumnType("decimal(6, 2)")
                        .HasComment("新主题的可能性");

                    b.Property<string>("ResponseFormat")
                        .HasColumnType("json")
                        .HasComment("输出格式");

                    b.Property<string>("Stop")
                        .HasColumnType("json")
                        .HasComment("停止词集合");

                    b.Property<bool?>("Stream")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否启用流式输出");

                    b.Property<string>("StreamOption")
                        .HasColumnType("json")
                        .HasComment("流式输出选项");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text")
                        .HasComment("系统提示");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(6, 2)")
                        .HasComment("采样温度");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<int?>("TopLogprobs")
                        .HasColumnType("int")
                        .HasComment("返回所输出概率 top N 的 token 的对数概率");

                    b.Property<decimal?>("TopP")
                        .HasColumnType("decimal(6, 2)")
                        .HasComment("采样概率");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("DeepSeekConfig", null, t =>
                        {
                            t.HasComment("DeepSeek参数配置");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
