// <auto-generated />
using System;
using HaoKao.QuestionService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.QuestionService.Infrastructure.Migrations
{
    [DbContext(typeof(QuestionDbContext))]
    [Migration("20241216074630_AddQuestionWrongSort")]
    partial class AddQuestionWrongSort
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.DailyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建日期");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)")
                        .HasComment("试题Id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "CreateDate", "TenantId")
                        .IsUnique();

                    b.ToTable("DailyQuestion", null, t =>
                        {
                            t.HasComment("每日一题");
                        });
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AbilityIds")
                        .HasMaxLength(360)
                        .HasColumnType("varchar")
                        .HasComment("能力维度id");

                    b.Property<Guid?>("ChapterNodeId")
                        .HasColumnType("char(36)")
                        .HasComment("章节Id");

                    b.Property<string>("ChapterNodeName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("章节名称");

                    b.Property<long>("CorrectCount")
                        .HasColumnType("bigint")
                        .HasComment("答对次数");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("EnableState")
                        .HasColumnType("int")
                        .HasComment("启用状态");

                    b.Property<int?>("FreeState")
                        .HasColumnType("int")
                        .HasComment("免费分区");

                    b.Property<string>("MediaAnalysis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasComment("音视频解析");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasComment("父题目Id");

                    b.Property<Guid>("QuestionCategoryId")
                        .HasColumnType("char(36)")
                        .HasComment("试题分类Id");

                    b.Property<string>("QuestionCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("试题分类名称");

                    b.Property<string>("QuestionOptions")
                        .HasColumnType("json")
                        .HasComment("试题选项");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("试题内容 (题干)");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasComment("试题标题 (管理端使用)");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("char(36)")
                        .HasComment("试题类型Id");

                    b.Property<string>("QuestionTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("试题类型名称");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TextAnalysis")
                        .HasColumnType("longtext")
                        .HasComment("文字解析");

                    b.Property<string>("TrialQuestionId")
                        .HasColumnType("varchar(50)")
                        .HasComment("命审题Id");

                    b.Property<long>("WrongCount")
                        .HasColumnType("bigint")
                        .HasComment("答错次数");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("QuestionTitle");

                    b.HasIndex("SubjectId", "ChapterNodeId", "QuestionCategoryId", "TenantId");

                    b.ToTable("Question", null, t =>
                        {
                            t.HasComment("试题");
                        });
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "CreatorId", "TenantId");

                    b.ToTable("QuestionCollection", (string)null);
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionCourseVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)")
                        .HasComment("试题Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("char(36)")
                        .HasComment("视频Id");

                    b.Property<string>("VideoName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasComment("视频名称");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasComment("视频Url");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.HasIndex("VideoId", "TenantId");

                    b.ToTable("QuestionCourseVideo", null, t =>
                        {
                            t.HasComment("试题课程视频");
                        });
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionKnowledgePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("KnowledgePointId")
                        .HasColumnType("char(36)")
                        .HasComment("知识点Id");

                    b.Property<string>("KnowledgePointName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("知识点名称");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)")
                        .HasComment("试题Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("KnowledgePointId", "KnowledgePointName", "TenantId");

                    b.ToTable("QuestionKnowledgePoint", null, t =>
                        {
                            t.HasComment("试题知识点");
                        });
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionWrong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ParentQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasComment("父试题Id");

                    b.Property<Guid>("ParentQuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasComment("父试题类型Id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("char(36)")
                        .HasComment("试题类型Id");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "CreatorId", "TenantId");

                    b.HasIndex("QuestionId", "CreatorId", "QuestionTypeId", "ParentQuestionTypeId", "TenantId");

                    b.ToTable("QuestionWrong", (string)null);
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionWrongPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("创建人Id");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("下载地址");

                    b.Property<string>("PaperName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("试卷名称");

                    b.Property<int>("QuestionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("试题数量");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasComment("科目Id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "CreatorId", "CreateTime", "TenantId")
                        .IsUnique();

                    b.ToTable("QuestionWrongPaper", (string)null);
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.UnionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChapterNodeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("SubjectId", "QuestionCategoryId", "TenantId");

                    b.ToTable("UnionQuestion", (string)null);
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionCollection", b =>
                {
                    b.HasOne("HaoKao.QuestionService.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionCourseVideo", b =>
                {
                    b.HasOne("HaoKao.QuestionService.Domain.Entities.Question", null)
                        .WithOne("CourseVideo")
                        .HasForeignKey("HaoKao.QuestionService.Domain.Entities.QuestionCourseVideo", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionKnowledgePoint", b =>
                {
                    b.HasOne("HaoKao.QuestionService.Domain.Entities.Question", null)
                        .WithMany("KnowledgePoints")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.QuestionWrong", b =>
                {
                    b.HasOne("HaoKao.QuestionService.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HaoKao.QuestionService.Domain.Entities.Question", b =>
                {
                    b.Navigation("CourseVideo");

                    b.Navigation("KnowledgePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
