// <auto-generated />
using System;
using HaoKao.CampaignService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.CampaignService.Infrastructure.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    [Migration("20240704054312_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.CampaignService.Domain.Entities.GiftBag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("活动名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("结束时间");

                    b.Property<int>("GiftType")
                        .HasColumnType("int")
                        .HasComment("礼包类型");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否发布");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasComment("产品Id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("产品名称");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int")
                        .HasComment("领取数量");

                    b.Property<string>("ReceiveRules")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasComment("领取规则");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("开始时间");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("修改时间");

                    b.Property<string>("WeChatMiniProgramImageSet")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasComment("微信小程序图片");

                    b.Property<string>("WebSiteImageSet")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasComment("PC网站图片");

                    b.HasKey("Id");

                    b.HasIndex("CampaignName", "GiftType");

                    b.ToTable("GiftBag", (string)null);
                });

            modelBuilder.Entity("HaoKao.CampaignService.Domain.Entities.GiftBagReceiveLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("活动名称");

                    b.Property<Guid>("GiftBagId")
                        .HasColumnType("char(36)")
                        .HasComment("礼包Id");

                    b.Property<int>("GiftType")
                        .HasColumnType("int")
                        .HasComment("礼包类型");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasComment("产品Id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("产品名称");

                    b.Property<DateTime>("ReceiveTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("领取时间");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("char(36)")
                        .HasComment("领取人Id");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("领取人名称");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("GiftBagId");

                    b.HasIndex("ReceiverName", "ReceiveTime");

                    b.ToTable("GiftBagReceiveLog", (string)null);
                });

            modelBuilder.Entity("HaoKao.CampaignService.Domain.Entities.GiftBagReceiveLog", b =>
                {
                    b.HasOne("HaoKao.CampaignService.Domain.Entities.GiftBag", null)
                        .WithMany("GiftBagReceiveLogs")
                        .HasForeignKey("GiftBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.CampaignService.Domain.Entities.GiftBag", b =>
                {
                    b.Navigation("GiftBagReceiveLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
