// <auto-generated />
using System;
using HaoKao.OpenPlatformService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaoKao.OpenPlatformService.Infrastructure.Migrations
{
    [DbContext(typeof(OpenPlatformDbContext))]
    [Migration("20230819095940_editSigningAlgorithms")]
    partial class editSigningAlgorithms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AbsoluteRefreshTokenLifetime")
                        .HasColumnType("int");

                    b.Property<int>("AccessTokenLifetime")
                        .HasColumnType("int");

                    b.Property<int>("AccessTokenType")
                        .HasColumnType("int");

                    b.Property<bool>("AllowAccessTokensViaBrowser")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowOfflineAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowPlainTextPkce")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowRememberConsent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AlwaysIncludeUserClaimsInIdToken")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AlwaysSendClientClaims")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AuthorizationCodeLifetime")
                        .HasColumnType("int");

                    b.Property<bool>("BackChannelLogoutSessionRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BackChannelLogoutUri")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ClientClaimsPrefix")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientUri")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("ConsentLifetime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DeviceCodeLifetime")
                        .HasColumnType("int");

                    b.Property<bool>("EnableLocalLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FrontChannelLogoutSessionRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FrontChannelLogoutUri")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("IdentityTokenLifetime")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeJwtId")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUri")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PairWiseSubjectSalt")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RefreshTokenExpiration")
                        .HasColumnType("int");

                    b.Property<int>("RefreshTokenUsage")
                        .HasColumnType("int");

                    b.Property<bool>("RequireClientSecret")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequireConsent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequirePkce")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequireRequestObject")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SlidingRefreshTokenLifetime")
                        .HasColumnType("int");

                    b.Property<bool>("UpdateAccessTokenClaimsOnRefresh")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UserCodeType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UserSsoLifetime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("AccessClient", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientClaim", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientCorsOrigin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientCorsOrigins");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientGrantType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientGrantType", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientIdPRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientIdPRestriction", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientPostLogoutRedirectUri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PostLogoutRedirectUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientPostLogoutRedirectUri", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientProperties");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientRedirectUri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientRedirectUri", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientScope", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientSecret", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientSigningAlgorithm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SigningAlgorithm")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("AccessClientSigningAlgorithm", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.DailyActiveUserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("活跃的客户端Id");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasComment("活跃的日期(yyyy-MM-dd)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasComment("用户Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientId", "CreateDate", "CreateTime");

                    b.ToTable("DailyActiveUserLog", (string)null);

                    b.HasComment("用户每日活跃记录");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.DomainProxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccessClientId");

                    b.ToTable("DomainProxy", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("varchar(1000)")
                        .HasComment("其它信息");

                    b.Property<Guid?>("RegisterUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Scheme")
                        .HasColumnType("varchar(20)")
                        .HasComment("平台名称");

                    b.Property<string>("UniqueIdentifier")
                        .HasColumnType("varchar(100)")
                        .HasComment("唯一标识");

                    b.HasKey("Id");

                    b.HasIndex("RegisterUserId");

                    b.HasIndex("UniqueIdentifier", "Scheme")
                        .IsUnique();

                    b.ToTable("ExternalIdentity", (string)null);
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.RegisterUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .HasColumnType("varchar(30)")
                        .HasComment("用户账号");

                    b.Property<string>("ClientId")
                        .HasColumnType("longtext")
                        .HasComment("客户端Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("varchar(40)")
                        .HasComment("邮箱地址");

                    b.Property<string>("HeadImage")
                        .HasColumnType("varchar(200)")
                        .HasComment("头像");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("varchar(30)")
                        .HasComment("最后登录IP");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("最后登录时间");

                    b.Property<string>("NickName")
                        .HasColumnType("varchar(30)")
                        .HasComment("用户昵称");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(32)")
                        .HasComment("密码");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(11)")
                        .HasComment("手机号码");

                    b.Property<int>("UserGender")
                        .HasColumnType("int")
                        .HasComment("用户性别");

                    b.Property<int>("UserState")
                        .HasColumnType("int")
                        .HasComment("用户状态");

                    b.HasKey("Id");

                    b.HasIndex("Phone", "Account", "NickName", "UserState", "CreateTime");

                    b.ToTable("RegisterUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2ead372-8c6a-4c52-9f17-9d1599f202f0"),
                            Account = "tempuser",
                            CreateTime = new DateTime(2023, 8, 19, 17, 59, 39, 939, DateTimeKind.Local).AddTicks(5195),
                            EmailAddress = "13000000000@qq.com",
                            LastLoginTime = new DateTime(2023, 8, 19, 17, 59, 39, 939, DateTimeKind.Local).AddTicks(5193),
                            NickName = "临时用户",
                            Password = "E10ADC3949BA59ABBE56E057F20F883E",
                            Phone = "13000000000",
                            UserGender = 0,
                            UserState = 1
                        });
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientClaim", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("Claims")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientCorsOrigin", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("AllowedCorsOrigins")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientGrantType", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("AllowedGrantTypes")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientIdPRestriction", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("IdentityProviderRestrictions")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientPostLogoutRedirectUri", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("PostLogoutRedirectUris")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientProperty", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("Properties")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientRedirectUri", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("RedirectUris")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientScope", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("AllowedScopes")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientSecret", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("ClientSecrets")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClientSigningAlgorithm", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("AllowedIdentityTokenSigningAlgorithms")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.DomainProxy", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", "AccessClient")
                        .WithMany("DomainProxies")
                        .HasForeignKey("AccessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClient");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.ExternalIdentity", b =>
                {
                    b.HasOne("HaoKao.OpenPlatformService.Domain.Entities.RegisterUser", "RegisterUser")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("RegisterUserId");

                    b.Navigation("RegisterUser");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.AccessClient", b =>
                {
                    b.Navigation("AllowedCorsOrigins");

                    b.Navigation("AllowedGrantTypes");

                    b.Navigation("AllowedIdentityTokenSigningAlgorithms");

                    b.Navigation("AllowedScopes");

                    b.Navigation("Claims");

                    b.Navigation("ClientSecrets");

                    b.Navigation("DomainProxies");

                    b.Navigation("IdentityProviderRestrictions");

                    b.Navigation("PostLogoutRedirectUris");

                    b.Navigation("Properties");

                    b.Navigation("RedirectUris");
                });

            modelBuilder.Entity("HaoKao.OpenPlatformService.Domain.Entities.RegisterUser", b =>
                {
                    b.Navigation("ExternalIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
