// <auto-generated />
using System;
using HaoKao.NoticeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.NoticeService.Infrastructure.Migrations
{
    [DbContext(typeof(NoticeDbContext))]
    [Migration("20240119071934_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.NoticeService.Domain.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("公告内容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)")
                        .HasComment("创建人名称");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("弹出结束时间");

                    b.Property<bool>("Popup")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否弹出");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否发布");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("弹出开始时间");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("租户Id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("公告名称");

                    b.HasKey("Id");

                    b.ToTable("Notice", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
