// <auto-generated />
using System;
using HaoKao.BasicService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaoKao.BasicService.Infrastructure.Migrations
{
    [DbContext(typeof(BasicDbContext))]
    [Migration("20240416061404_ChangeColumnType")]
    partial class ChangeColumnType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.BasalPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("AllowMask")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AppliedId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppliedObjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("AppliedObjectType")
                        .HasColumnType("int");

                    b.Property<long>("DenyMask")
                        .HasColumnType("bigint");

                    b.Property<int>("ValidateObjectId")
                        .HasColumnType("int");

                    b.Property<int>("ValidateObjectType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppliedId");

                    b.HasIndex("AppliedObjectId");

                    b.HasIndex("AppliedObjectType");

                    b.HasIndex("ValidateObjectId");

                    b.HasIndex("ValidateObjectType");

                    b.ToTable("BasalPermission", (string)null);
                });

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Desc")
                        .HasColumnType("varchar(200)")
                        .HasComment("角色描述");

                    b.Property<ulong>("IsInitData")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)")
                        .HasComment("角色名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70ecc373-16f7-42e9-b31b-e80507b7c20a"),
                            Desc = "考试管理员具有的该角色",
                            IsInitData = 1ul,
                            Name = "考试管理员角色",
                            TenantId = "00000000-0000-0000-0000-000000000000"
                        });
                });

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.ServiceDataRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityDesc")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ExpressionType")
                        .HasColumnType("int");

                    b.Property<string>("FieldDesc")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FieldName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FieldType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FieldValue")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceDataRule", (string)null);
                });

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.ServicePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("FuncModule")
                        .HasColumnType("bigint");

                    b.Property<string>("OperationPermissions")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OtherParams")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tag")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServicePermission", (string)null);
                });

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AuthorizeType")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<ulong>("IsInitData")
                        .HasColumnType("bit");

                    b.Property<Guid>("OtherId")
                        .HasColumnType("char(36)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TenantName")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserAccount")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccount", "TenantId")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("58205e0e-1552-4282-bedc-a92d0afb37df"),
                            AuthorizeType = 0,
                            CreateTime = new DateTime(2024, 4, 16, 14, 14, 4, 686, DateTimeKind.Local).AddTicks(8180),
                            CreatorId = "58205e0e-1552-4282-bedc-a92d0afb37df",
                            IsInitData = 1ul,
                            OtherId = new Guid("00000000-0000-0000-0000-000000000000"),
                            State = 0,
                            TenantId = "00000000-0000-0000-0000-000000000000",
                            TenantName = "系统管理",
                            UserAccount = "systemsuperadmin",
                            UserName = "系统管理员",
                            UserPassword = "21232F297A57A5A743894A0E4A801FC3",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.UserRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityDesc")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ExpressionType")
                        .HasColumnType("int");

                    b.Property<string>("FieldDesc")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FieldName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FieldType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text");

                    b.Property<string>("FieldValueText")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRule", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("char(36)");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.UserRule", b =>
                {
                    b.HasOne("HaoKao.BasicService.Domain.Models.User", null)
                        .WithMany("RulesList")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("HaoKao.BasicService.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaoKao.BasicService.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaoKao.BasicService.Domain.Models.User", b =>
                {
                    b.Navigation("RulesList");
                });
#pragma warning restore 612, 618
        }
    }
}
