// <auto-generated />
using System;
using HaoKao.PaperService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.PaperService.Infrastructure.Migrations
{
    [DbContext(typeof(PaperDbContext))]
    [Migration("20241122024351_AddYear")]
    partial class AddYear
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HaoKao.PaperService.Domain.Entities.Paper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("分类名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("IsFree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("试卷名称");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int")
                        .HasComment("总题数");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("及格分数");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StructJson")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasComment("科目名称");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(6,2)")
                        .HasComment("总分数");

                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2024)
                        .HasComment("年份");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "CategoryId", "TenantId");

                    b.ToTable("Paper", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
