// <auto-generated />
using System;
using HaoKao.PaperTempleteService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.PaperTempleteService.Infrastructure.Migrations
{
    [DbContext(typeof(PaperTempleteDbContext))]
    partial class PaperTempleteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.PaperTempleteService.Domain.Entities.PaperTemplete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("备注");

                    b.Property<string>("SuitableSubjects")
                        .HasColumnType("text")
                        .HasComment("适用科目");

                    b.Property<string>("TempleteName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("试卷模板名称");

                    b.Property<string>("TempleteStructDatas")
                        .HasColumnType("text")
                        .HasComment("模板结构");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("TempleteName", "TenantId");

                    b.ToTable("PaperTemplete", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
