// <auto-generated />
using System;
using HaoKao.TenantService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.TenantService.Infrastructure.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20230228005917_initTenantServiceDatabase")]
    partial class initTenantServiceDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.TenantService.Domain.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdminPhone")
                        .HasColumnType("varchar(36)")
                        .HasComment("租户管理员手机号码");

                    b.Property<string>("AdminUserAcount")
                        .HasColumnType("varchar(36)")
                        .HasComment("租户管理员账号");

                    b.Property<string>("AdminUserName")
                        .HasColumnType("varchar(36)")
                        .HasComment("租户管理员名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("说明");

                    b.Property<int>("ReleaseState")
                        .HasColumnType("int")
                        .HasComment("发布状态");

                    b.Property<int>("StartState")
                        .HasColumnType("int")
                        .HasComment("启用禁用状态");

                    b.Property<long>("SystemModule")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantName")
                        .HasColumnType("varchar(500)")
                        .HasComment("租户名称");

                    b.Property<string>("TenantNo")
                        .HasColumnType("varchar(20)")
                        .HasComment("租户编号或代码");

                    b.HasKey("Id");

                    b.ToTable("Tenant", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
