// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.DataDictionaryService.Infrastructure.Migrations
{
    [DbContext(typeof(DataDictionaryDbContext))]
    [Migration("20220316070904_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(225)");

                    b.Property<string>("PName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Pid")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<ulong?>("State")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Pid");

                    b.HasIndex("State");

                    b.HasIndex("Code", "Name", "TenantId")
                        .IsUnique();

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", b =>
                {
                    b.HasOne("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", null)
                        .WithMany("Children")
                        .HasForeignKey("Pid");
                });

            modelBuilder.Entity("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
