// <auto-generated />
using System;
using HaoKao.DataDictionaryService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaoKao.DataDictionaryService.Infrastructure.Migrations
{
    [DbContext(typeof(DataDictionaryDbContext))]
    [Migration("20231017092738_addAbility")]
    partial class addAbility
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(225)");

                    b.Property<string>("PName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Pid")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<ulong?>("State")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Pid");

                    b.HasIndex("State");

                    b.HasIndex("Code", "Name", "TenantId")
                        .IsUnique();

                    b.ToTable("Dictionaries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("08db395d-aeee-47d5-88eb-8a40315e1aad"),
                            Code = "el",
                            Name = "考试级别",
                            PName = "顶级节点",
                            Path = "考试级别",
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db395d-b5db-4dc5-888c-a73d184bc184"),
                            Code = "JJ9930",
                            Name = "经济师",
                            PName = "考试级别",
                            Path = "考试级别=>经济师",
                            Pid = new Guid("08db395d-aeee-47d5-88eb-8a40315e1aad"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db395d-bc27-4d09-86b5-c05dff7deb30"),
                            Code = "XF9930",
                            Name = "消防师",
                            PName = "考试级别",
                            Path = "考试级别=>消防师",
                            Pid = new Guid("08db395d-aeee-47d5-88eb-8a40315e1aad"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db395d-c06c-4875-86da-987b25dba9db"),
                            Code = "KJ9930",
                            Name = "会计师",
                            PName = "考试级别",
                            Path = "考试级别=>会计师",
                            Pid = new Guid("08db395d-aeee-47d5-88eb-8a40315e1aad"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9271-efed-48e6-8f86-6604089a8b6e"),
                            Code = "KC0415",
                            Name = "课程对比",
                            PName = "顶级节点",
                            Path = "课程对比",
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9271-fb47-47e0-8794-481bc7a83aac"),
                            Code = "KG6752",
                            Name = "适合人群",
                            PName = "课程对比",
                            Path = "课程对比=>适合人群",
                            Pid = new Guid("08db9271-efed-48e6-8f86-6604089a8b6e"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9271-fef4-4d75-8b1d-daf9ac8bb250"),
                            Code = "JX7250",
                            Name = "教学模块",
                            PName = "课程对比",
                            Path = "课程对比=>教学模块",
                            Pid = new Guid("08db9271-efed-48e6-8f86-6604089a8b6e"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-624c-4b91-8262-b063d4052f84"),
                            Code = "JC9970",
                            Name = "基础阶段",
                            PName = "教学模块",
                            Path = "课程对比=>教学模块=>基础阶段",
                            Pid = new Guid("08db9271-fef4-4d75-8b1d-daf9ac8bb250"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-651e-47bd-8b73-658fbc71f2d3"),
                            Code = "JH1096",
                            Name = "强化阶段",
                            PName = "教学模块",
                            Path = "课程对比=>教学模块=>强化阶段",
                            Pid = new Guid("08db9271-fef4-4d75-8b1d-daf9ac8bb250"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-6790-4200-80c2-b56431104573"),
                            Code = "CC9246",
                            Name = "冲刺阶段",
                            PName = "教学模块",
                            Path = "课程对比=>教学模块=>冲刺阶段",
                            Pid = new Guid("08db9271-fef4-4d75-8b1d-daf9ac8bb250"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-6ac8-4707-83f1-f827f086f932"),
                            Code = "PS3711",
                            Name = "评审阶段",
                            PName = "教学模块",
                            Path = "课程对比=>教学模块=>评审阶段",
                            Pid = new Guid("08db9271-fef4-4d75-8b1d-daf9ac8bb250"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-02e9-40f2-8627-5de8abd96dbb"),
                            Code = "ZX1641",
                            Name = "助学模块",
                            PName = "课程对比",
                            Path = "课程对比=>助学模块",
                            Pid = new Guid("08db9271-efed-48e6-8f86-6604089a8b6e"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-738b-436d-8502-29575be4bd4a"),
                            Code = "BZ6107",
                            Name = "班主任督学",
                            PName = "助学模块",
                            Path = "课程对比=>助学模块=>班主任督学",
                            Pid = new Guid("08db9272-02e9-40f2-8627-5de8abd96dbb"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-76e6-4071-890f-1417fcb49981"),
                            Code = "ZX3244",
                            Name = "在线题库",
                            PName = "助学模块",
                            Path = "课程对比=>助学模块=>在线题库",
                            Pid = new Guid("08db9272-02e9-40f2-8627-5de8abd96dbb"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-79e9-4541-8976-4b64ed4478f1"),
                            Code = "FZ8704",
                            Name = "仿真模考测评",
                            PName = "助学模块",
                            Path = "课程对比=>助学模块=>仿真模考测评",
                            Pid = new Guid("08db9272-02e9-40f2-8627-5de8abd96dbb"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-05ea-4d4e-8466-b7ceaaf9e158"),
                            Code = "JX5456",
                            Name = "教学资料",
                            PName = "课程对比",
                            Path = "课程对比=>教学资料",
                            Pid = new Guid("08db9271-efed-48e6-8f86-6604089a8b6e"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-8141-4584-82d4-f0a14dcba4a4"),
                            Code = "KJ8174",
                            Name = "课件讲义",
                            PName = "教学资料",
                            Path = "课程对比=>教学资料=>课件讲义",
                            Pid = new Guid("08db9272-05ea-4d4e-8466-b7ceaaf9e158"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-83b4-462f-8fa7-9b9e1614b90c"),
                            Code = "KS7049",
                            Name = "考试大纲",
                            PName = "教学资料",
                            Path = "课程对比=>教学资料=>考试大纲",
                            Pid = new Guid("08db9272-05ea-4d4e-8466-b7ceaaf9e158"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-85fb-4156-82fe-69186401b3d1"),
                            Code = "JT07377",
                            Name = "其他",
                            PName = "教学资料",
                            Path = "课程对比=>教学资料=>其他",
                            Pid = new Guid("08db9272-05ea-4d4e-8466-b7ceaaf9e158"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-0867-41f5-89f5-9a57f4f49012"),
                            Code = "TS9189",
                            Name = "特色服务",
                            PName = "课程对比",
                            Path = "课程对比=>特色服务",
                            Pid = new Guid("08db9271-efed-48e6-8f86-6604089a8b6e"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-8abf-4099-8400-b2dcac2be4ca"),
                            Code = "XD2732",
                            Name = "续读协议",
                            PName = "特色服务",
                            Path = "课程对比=>特色服务=>续读协议",
                            Pid = new Guid("08db9272-0867-41f5-89f5-9a57f4f49012"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9272-0aed-4ab8-81dc-ace77bea8494"),
                            Code = "JG69532",
                            Name = "价格",
                            PName = "课程对比",
                            Path = "课程对比=>价格",
                            Pid = new Guid("08db9271-efed-48e6-8f86-6604089a8b6e"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db94bc-4eda-44e0-8b47-dd2e04233faf"),
                            Code = "XD0266",
                            Name = "续读原因",
                            PName = "顶级节点",
                            Path = "续读原因",
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db94bc-6fdb-442b-8c29-4cad6d478fdd"),
                            Code = "KS0862",
                            Name = "考试未通过",
                            PName = "续读原因",
                            Path = "续读原因=>考试未通过",
                            Pid = new Guid("08db94bc-4eda-44e0-8b47-dd2e04233faf"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db94bc-7408-4ef7-807e-c25a7ee3395e"),
                            Code = "TS9519",
                            Name = "特殊原因缺考",
                            PName = "续读原因",
                            Path = "续读原因=>特殊原因缺考",
                            Pid = new Guid("08db94bc-4eda-44e0-8b47-dd2e04233faf"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db94bc-7732-4071-8723-a0c8d3f1173d"),
                            Code = "BD0563",
                            Name = "本地区考试取消",
                            PName = "续读原因",
                            Path = "续读原因=>本地区考试取消",
                            Pid = new Guid("08db94bc-4eda-44e0-8b47-dd2e04233faf"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db94bc-7a93-4364-8757-e5e79055a7af"),
                            Code = "JT8748",
                            Name = "其他原因",
                            PName = "续读原因",
                            Path = "续读原因=>其他原因",
                            Pid = new Guid("08db94bc-4eda-44e0-8b47-dd2e04233faf"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db994f-e2e4-40d5-8ed4-18786bbf6e85"),
                            Code = "KC9613",
                            Name = "课程阶段",
                            PName = "顶级节点",
                            Path = "课程阶段",
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db994f-eaed-458a-81c0-a61cc0a094cb"),
                            Code = "JC1502",
                            Name = "基础阶段",
                            PName = "课程阶段",
                            Path = "课程阶段=>基础阶段",
                            Pid = new Guid("08db994f-e2e4-40d5-8ed4-18786bbf6e85"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db994f-eef1-4e74-8f38-828eccdb603e"),
                            Code = "JH1476",
                            Name = "强化阶段",
                            PName = "课程阶段",
                            Path = "课程阶段=>强化阶段",
                            Pid = new Guid("08db994f-e2e4-40d5-8ed4-18786bbf6e85"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db994f-f5cb-47fa-861a-80a53511aba8"),
                            Code = "CC5084",
                            Name = "冲刺阶段",
                            PName = "课程阶段",
                            Path = "课程阶段=>冲刺阶段",
                            Pid = new Guid("08db994f-e2e4-40d5-8ed4-18786bbf6e85"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db994f-fecf-42b8-87d5-41d7a0da7ac7"),
                            Code = "PS6299",
                            Name = "评审阶段",
                            PName = "课程阶段",
                            Path = "课程阶段=>评审阶段",
                            Pid = new Guid("08db994f-e2e4-40d5-8ed4-18786bbf6e85"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08db9950-037a-4b9d-86c4-472c075235d9"),
                            Code = "JT29225",
                            Name = "其它",
                            PName = "课程阶段",
                            Path = "课程阶段=>其它",
                            Pid = new Guid("08db994f-e2e4-40d5-8ed4-18786bbf6e85"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Code = "RD0740",
                            Name = "热点类型",
                            PName = "顶级节点",
                            Path = "热点类型",
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-6e0d-4fd5-8eb3-2d281483f10f"),
                            Code = "KS8313",
                            Name = "考试大纲",
                            PName = "热点类型",
                            Path = "热点类型=>考试大纲",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-7138-4013-8d26-18f6f3a1362b"),
                            Code = "TS4849",
                            Name = "图书发售",
                            PName = "热点类型",
                            Path = "热点类型=>图书发售",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-73a5-4dae-822d-b43f65f9433d"),
                            Code = "KS3233",
                            Name = "考试报名",
                            PName = "热点类型",
                            Path = "热点类型=>考试报名",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-75ba-423c-82eb-8ad5c2ed1630"),
                            Code = "XX1600",
                            Name = "学习备考",
                            PName = "热点类型",
                            Path = "热点类型=>学习备考",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-782f-4fdd-8258-2533aec6727d"),
                            Code = "ZK7113",
                            Name = "准考证",
                            PName = "热点类型",
                            Path = "热点类型=>准考证",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-a8b7-49a4-8ffa-efb7dcfe7164"),
                            Code = "KS9201",
                            Name = "考试时间",
                            PName = "热点类型",
                            Path = "热点类型=>考试时间",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-ac1d-4976-8055-ce8a2afdad7b"),
                            Code = "CJ4608",
                            Name = "成绩查询",
                            PName = "热点类型",
                            Path = "热点类型=>成绩查询",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbceda-aefb-4a07-82f9-f2796027cc06"),
                            Code = "ZS0482",
                            Name = "证书领取",
                            PName = "热点类型",
                            Path = "热点类型=>证书领取",
                            Pid = new Guid("08dbceda-3f6b-4ae2-8493-9466c54511df"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbcee8-a725-4dec-87b1-13d5be8c4cdd"),
                            Code = "NL4892",
                            Name = "能力维度",
                            PName = "顶级节点",
                            Path = "能力维度",
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbcee9-1ac2-4a94-8d53-e04da0eee147"),
                            Code = "JS2336",
                            Name = "计算能力",
                            PName = "能力维度",
                            Path = "能力维度=>计算能力",
                            Pid = new Guid("08dbcee8-a725-4dec-87b1-13d5be8c4cdd"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbcee9-2047-4f57-809f-2129bedadb2c"),
                            Code = "LX7165",
                            Name = "练习速度",
                            PName = "能力维度",
                            Path = "能力维度=>练习速度",
                            Pid = new Guid("08dbcee8-a725-4dec-87b1-13d5be8c4cdd"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbcee9-233f-494b-8293-0e902b5d3489"),
                            Code = "PD9144",
                            Name = "判断能力",
                            PName = "能力维度",
                            Path = "能力维度=>判断能力",
                            Pid = new Guid("08dbcee8-a725-4dec-87b1-13d5be8c4cdd"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbcee9-2576-4dd9-8efb-52510251fd14"),
                            Code = "FX6064",
                            Name = "分析能力",
                            PName = "能力维度",
                            Path = "能力维度=>分析能力",
                            Pid = new Guid("08dbcee8-a725-4dec-87b1-13d5be8c4cdd"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbcee9-2798-4721-8795-7174a432323f"),
                            Code = "LJ6732",
                            Name = "理解能力",
                            PName = "能力维度",
                            Path = "能力维度=>理解能力",
                            Pid = new Guid("08dbcee8-a725-4dec-87b1-13d5be8c4cdd"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("08dbcee9-29c2-4f1a-8fcd-866667b83d77"),
                            Code = "JY4523",
                            Name = "记忆能力",
                            PName = "能力维度",
                            Path = "能力维度=>记忆能力",
                            Pid = new Guid("08dbcee8-a725-4dec-87b1-13d5be8c4cdd"),
                            Sort = 0,
                            State = 1ul,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", b =>
                {
                    b.HasOne("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", null)
                        .WithMany("Children")
                        .HasForeignKey("Pid");
                });

            modelBuilder.Entity("HaoKao.DataDictionaryService.Domain.Models.Dictionaries", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
